### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral#111]
As I sen, `maestral` is heading for a 1.0.0 release. Presumably, this is considered stable (enough). I am opening this to discuss packaging for `Arch Linux` (and derivatives) through [AUR](https://aur.archlinux.org/).

There is already a git [package](https://aur.archlinux.org/packages/maestral-git/), but it is missing some recent dependencies, etc. I have tried to get in touch with the owner, and potentially be co-maintainer. If this fails, I could start a new package with released versions.

Here is a sample PKGBUILD for the cli component, based on previous work:
```
_srcname='maestral-dropbox'

pkgname='maestral'
provides=('maestral')
conflicts=('maestral-git')
pkgver=0.6.4
pkgrel=1
pkgdesc='A light-weight and open-source CLI Dropbox client.'
arch=('x86_64')
url="https://github.com/SamSchott/${_srcname}"
license=('MIT')
source=("${url}/archive/v${pkgver}.tar.gz")
makedepends=('python-setuptools')
depends=(
    'python>=3.8'
    'python-atomicwrites'
    'python-blinker'
    'python-bugsnag'
    'python-click>=7.0'
    'python-dropbox>=9.4.0'
    'python-keyring>=19.0.0'
    'python-keyrings-alt>=3.0.0'
    'python-lockfile'
    'python-pyro5'
    'python-requests'
    'python-u-msgpack'
    'python-watchdog>=0.9.0'
    'python-systemd')
md5sums=('SKIP')

build() {
    cd "${srcdir}/${_srcname}-${pkgver}"
    python setup.py build
}

package() {
    cd "${srcdir}/${_srcname}-${pkgver}"
    # Run python setup function
    python setup.py install --root="${pkgdir}/" --optimize=1 --skip-build
    # Remove icons, unnecessary for the CLI
    rm -rf "${pkgdir}/usr/share/icons"
    # Install the licence
    install -Dm644 "${srcdir}/${_srcname}-${pkgver}/LICENSE.txt" \
    	"${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
```
I have tested, and it locally builds OK, but outside testing is always appreciated.

 I have some questions for the long-run health of packaging:
- The releases will follow the same pattern in the future, i.e., tar files appearing in the archive subfolder, etc?
- I would prefer dependencies to be maintained "official" packages, outside of AUR. RIght now, the only ones that only appear in AUR (and are not official) are `pyro5` and `bugsnag`. I will ask about plans to support `pyro5`, since right now `pyro4` is [officially](https://www.archlinux.org/packages/community/any/python-pyro/) maintained. I am less optimistic on `bugsnag` for the future. Since this does not look like a hard dependency, could it be removed in a stable version?
- Minimum version dependencies are easy to handle in Arch, since the latest versions of packages are provided faster than other distros. I am worried about maximum version dependencies (such as `dropbox<=9.5.0`) because they can break packages easily.
- If possible, mention in the changelog when dependencies change (add/remove) in order to ease the update of `PKGBUILD`, accordingly.
- regarding package naming: one could go with `maestral`, `maestral-cli`, `maestral-dropbox`, `maestral-dropbox-cli`. Any preference?

**Comment by SamSchott** [comment]
Stability and performance have indeed improved significantly in the last few releases and a 1.0.0 release should hopefully come out some time this month. And thank you for taking the time to package this. I have found that packaging for Linux really is a tedious job while trying to create a snap and a deb package. I can imagine that the current maintainer may have run into similar issues such as missing dependencies.

To answer your questions:

* Yes, releases will continue to follow the same pattern. The tar files are created automatically by Github on every release and Maestral uses github APIs to notify the user of new releases.

* I agree that there are good chances for Pyro5 to be officially maintained, at least once the author guarantees API stability. Bugsnag has been invaluable in getting reports from those who do not have a github account and for catching corner cases. It is one of the reasons why I am confident about the stability. But you are right, it is not packaged for most Linux distros since it is a subscription service (with a free plan for open source projects). Is there any way of bundling bugsnag with maestral when packaging? I know it wouldn't be ideal...

* The maximum version dependency is there to avoid breaking changes in the Dropbox SDK which have already occurred once. But I will aim to always test the newest Dropbox SDK as it is released.

* This is a good point. I will explicitly list changed decencies in the future. In 1.0.0, at least u-msgpack will be dropped. 

* Definite preference for just `maestral`, following the Python package name. Naming the repository "maestral-dropbox" was bid for higher visibility which I am starting to regret...

Finally, I expect that the pace of releases will slow down from 1.0.0 onwards. That should make the job of maintaining a package easier :)

**Comment by coxackie** [comment]
Many thanks for the prompt response, and for your great work on this. At this moment `bugsnag` is not a problem, as there is a further AUR [package](https://aur.archlinux.org/packages/python-bugsnag-git/). But I am worried about the long-run health, as I mentioned. Another option is to make bugsnag an optional dependency, but bundle it by default in the deb, snap, etc packages that you will provide. Arch users will not have a problem to give you info through Github.

I will wait for 1.0.0 to be out and then create the packages.

**Comment by bbaserdem** [comment]
As the maintainer; I'm waiting for stable release because I can't keep up with architectural/dependency changes. The project rapidly evolves, for the better.

I did add @coxackie as a comaintainer; but I am opposed to splitting isno 2 packages for cli and gui. I rather have one pkgbuild create 2 packages (split packaging) but I am waiting for a 1.0 version.

**Comment by coxackie** [comment]
In my opinion, we should respect the fact the the cli and gui are separate now. We should further accommodate those who do not want to install gui and pull all the `Qt` dependencies that will come with it. For example, I do not have `qt-base` installed (and do not wish to, as well).

**Comment by SamSchott** [comment]
There are a few reasons for splitting gui and daemon + cli, at least for the Python packages:

1. As @coxackie notes, many users only require the daemon and don't want to install Qt / PyQt. This isn't a serious issue for python packages since PyQt5 used to be an optional dependency before the split.

2. A native Cocoa GUI for macOS is in development. Splitting GUI and daemon makes it easier to develop different GUIs independently.

3. Once the daemon API is stable, GUI development can progress at its own pace instead of being tied to daemon releases.

For the macOS app bundle, I have made the decision to package GUI and daemon together but this has a different target audience than Linux. I think it really comes down to accommodating the most frequent use cases so for Linux I would probably tend towards separate packages. But this is by no means set in stone.

**Comment by bbaserdem** [comment]
In favor of maybe someone else providing other gui frontends (such as a web interface, or gtk) I think splitting the packages into maestral and maestral-qt makes sense. The current build script for the main daemon is up [here](https://aur.archlinux.org/packages/maestral-git/); and I am adding the qt script once I confirm it is working.

I also submitted packages for pyro5 and bugsnag directly from their pypi counterparts. They are not shipped with archlinux at least that I know. For end users; i understand that bugsnag is free? And you have a subscription as a collector of bug reports?

Archlinux community repos usually keep packages as up to date as possible. However; for programs that do use old versions (I just finished packaging matlab as well; which uses gcc6 which is no longer provided in the archrepos) submitting AUR old version builds is an acceptable solution.

**Comment by peterhoeg** [comment]
For reference, you can have a look at the packaging we do for NixOS: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/maestral/default.nix

It's been a part of NixOS since 0.2.6 and keeping it updated has been a breeze. But then again, packaging on NixOS is very pleasant to begin with... ;-)

On the issue of `bugsnag`, maybe not making it a hard requirement would be an option if that is the main barrier for distributions to start packaging it officially? Load it if it's there and otherwise just don't if it isn't.

**Comment by coxackie** [comment]
Please refer to:
https://aur.archlinux.org/packages/maestral/
https://aur.archlinux.org/packages/maestral-qt/
for the packaging of maestral (cli and gui versions, respectively) in the AUR (for Arch-based distros)

 This issue can be closed at any time - I leave it to @SamSchott.

**Comment by SamSchott** [comment]
Nice, thanks for the info. And for packaging of course!
