### ISSUE TITLE
[BUG] Recently files menu not showing

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#118]
**Describe the bug**

Recently files menu not showing when clicking it.

Mac Catalina 10.15.4
Maestral v0.6.4

<img width="268" alt="image" src="https://user-images.githubusercontent.com/3340367/79055908-6e23e080-7c59-11ea-8e99-fb034dffe819.png">

**To Reproduce**
Steps to reproduce the behaviour.

**Expected behaviour**

**System (please complete the following information):**
 - Maestral version:
 - OS: [e.g. Ubuntu]
 - Desktop environment: [e.g. Gnome 3.32]
 - Qt version:

**Additional context**

**Comment by cotfas** [comment]
Or it does not reflect all the latest changes..

<img width="343" alt="image" src="https://user-images.githubusercontent.com/3340367/79057345-36249980-7c69-11ea-8ec1-3977df4548b4.png">

*Maybe also a timestamp will be nice, and better, instead of hovering the menu, to add the latest changes directly in the main menu as gray out.

**Comment by SamSchott** [comment]
Yes, thats a known issue which has already been fixed in the development branch. At the moment, only remote file changes will be listed and local ones are missing.

Showing all changes in the main menu may be too much since Maestral at the moment shows the last 30 changes. However, time stamps could be a good idea.
