### ISSUE TITLE
Feature Request - show error in notification

### ISSUE THREAD

**Issue by peterhoeg** [SamSchott/maestral#160]
If the syncer daemon throws as error, maestral will helpfully show a notification that "maestral has failed" but it would be very nice if it could actually show the error directly.

In my case it was kwalletd5 that ended up having locked the keychain and thus maestral couldn't query it for the token:

It was clear from the journal what had gone wrong, but it would have been great if the notification had said "maestral has failed: Could not load access token. kwallet DBusKeyring is locked."

```
Jun 21 15:47:17 dolores maestral[33819]: Could not load access token. kwallet DBusKeyring is locked.
Jun 21 15:47:17 dolores maestral[33819]: Exception in thread maestral-update-check:
Jun 21 15:47:17 dolores maestral[33819]: Traceback (most recent call last):
Jun 21 15:47:17 dolores maestral[33819]:   File "/nix/store/40ndck76239fizlamm083nbz4ipnrbsm-maestral-1.0.3/lib/python3.8/site-packages/maestral/oauth.py", line 140, in _load_token
Jun 21 15:47:17 dolores maestral[33819]:     token = self.keyring.get_password('Maestral', self._account_id)
Jun 21 15:47:17 dolores maestral[33819]:   File "/nix/store/cnh6g5xxy4ddwq8kdvy2p4pr9vvl08hg-python3.8-keyring-20.0.1/lib/python3.8/site-packages/keyring/backends/kwallet.py", line 101, in get_password
Jun 21 15:47:17 dolores maestral[33819]:     raise KeyringLocked("Failed to unlock the keyring!")
Jun 21 15:47:17 dolores maestral[33819]: keyring.errors.KeyringLocked: Failed to unlock the keyring!
```

**Comment by SamSchott** [comment]
The notification which you are seeing is not actually from Maestral (I think) but rather from the ExecStopPost in the systemd service. Therefore it does not have any information about why the process failed.

There should be another notification before that, sent by Maestral itself, saying "Could not load access token. kwallet DBusKeyring is locked." because all log entries of level warning and higher are sent as notifications as well. Can you check your notification level with `maestral notify level`?  Possible values are `NONE|ERROR|SYNCISSUE|FILECHANGE`.

**Comment by peterhoeg** [comment]
Nicely spotted on the `ExecStopPost`. `maestral notify level` is set to `FILECHANGE` but there was no other maestral notification sent. Please note that this issue was reported some time ago and confirmed as being present in the latest version.

**Comment by SamSchott** [comment]
I have looked into this and was a bit confused at first because it clearly shows error messages on my machine. Both a desktop notification and an error message in `maestral status`:

```
Account:      sam.schott@outlook.com
Usage:        0.3% of 2.1 GB used
Status:       Could not load auth token, SecretService Keyring is locked
Sync threads: Stopped
Sync errors:  0


Could not load auth token, SecretService Keyring is locked
Please unlock the keyring and try again.
```

However, in my case the daemon also continued to run (without syncing) instead of crashing.

I believe the difference is that you start your daemon with systemd. When the keyring cannot be unlocked, maestral won't send a "READY" signal (at least not from the main process). Systemd will then stop the process, possibly before a notification is sent.

The underlying issue seems to be that linking and authentication is handled by a subprocess and systemd is currently configured not to accept any notifications from it.

**Comment by SamSchott** [comment]
I take that back, the main process of the service actually crashes before it can get a notification out because the exception is raised directly there.

I'll see if I can fix this but its low priority since the correct error is logged and the user does get notified that *something* went wrong.

**Comment by SamSchott** [comment]
So, I have moved all setup to the main process with `maestral start --foreground` and updated the linux implementation of desktop notifications to work without a running main loop. This should clean up the issues discussed here:

1.  Unexpected dbus notifications from a second process.
2. Missing desktop notifications for errors during setup.

This is currently out as a dev release v1.2.1.dev0 on PyPI. If you have some time, could you give it try?

**Comment by peterhoeg** [comment]
I'm going ahead to close as my previous test case (closed wallet) no longer exhibits this problem.
