### ISSUE TITLE
macOS Catalina notification support

### ISSUE THREAD

**Issue by yusuf8ahmed** [SamSchott/maestral#161]
Hi, 

you recently post a link your notification setup on toga [Here](https://github.com/beeware/toga/issues/907#issuecomment-638755649)😊 

I took as skim through the code and I have one question is it possible to create a notification on macOS Catalina using UNUserNotificationCenter with having/creating a signed app bundles

**Comment by SamSchott** [comment]
This question would be better suited for the issue that you linked to since it's not really related to Maestral.

To answer your questions: Yes, you can use both UNUserNotificationCenter and NSUserNotificationCenter in signed app bundles. It seems like UNUserNotificationCenter does not work *outside* of a signed bundle since macOS cannot validate which app the notification came from.

**Comment by yusuf8ahmed** [comment]
Do you know if there is any way to circumvent this???

**Comment by SamSchott** [comment]
Not that I know of, apart from using the deprecated `NSUserNotificationCenter`. Since the briefcase workflow and toga are both geared towards creating packaged apps, using `UNUserNotificationCenter` should however not be a problem. It just makes testing and development a bit harder.

**Comment by SamSchott** [comment]
I'll close this for now. If you have further questions, you can post them in https://github.com/beeware/toga/issues/907.
