### ISSUE TITLE
An easier way to retrieve file URLs

### ISSUE THREAD

**Issue by MatheusOPP** [SamSchott/maestral#213]
**Is your feature request related to a problem? Please describe.**
I'm currently using Maestral to sync my Dropbox files for both personal and professional use and it's working seamlessly. However, one pet peeve I have with it how difficult it is to get the URL for a particular file or folder for sharing. Every time, I need to access my account in the Dropbox site itself and navigate to the file/folder I want to share, then generate a link, due to the lack of an option to retrieve a link to it or generate a shareable link both through the CLI and file managers like Dolphin, which currently lack any kind of integration with Maestral.

**Describe the solution you'd like**
I am not sure if this is at all possible, but it would be interesting if there was a way to generate shareable URLs for a file/folder or to retrieve the URLs for files in the Dropbox site through some command in the CLI or through a right-button menu option in file managers (like Dolphin, which I use). I think the second case is a bit more complicated to implement due to the vast array of file managers that exist for Linux environments and the need to develop proper plugins/extensions for each of them, but even the first one would probably already facilitate the implementation of such a plugin by other people.

**Comment by SamSchott** [comment]
As you say, file manager integration will be quite involved as it requires writing extensions for the various file managers found on Linux. This will be more involved on macOS as well because Finder extensions need to be distributed as part of an app bundle.

However, supporting this in the CLI should be relatively straight forward. The Dropbox API provides endpoints to create and revoke links for sharing. It's just a question of wrapping the API calls and providing proper error handling.

**Comment by DMR-coding** [comment]
@SamSchott I'm interested in tackling this. Do you have contributing / devenv instructions somewhere?

**Comment by SamSchott** [comment]
@DMR-coding, that's good hear! I have just added contributing guidelines [here](https://github.com/SamSchott/maestral/blob/develop/CONTRIBUTING.md). In addition, the API docs will be a good reference to see how other commands are implemented.

I have already started implementing the first layer of support in the client module in the [shared-link-api](https://www.github.com/SamSchott/maestral/tree/shared-link-api) branch but have not gotten around to doing anything more. I'm very happy for you to take it from there. This issue is particularly good for newcomers because it does not touch the sync-engine (the most delicate part) but still spans many layers of the project.

The layers which are required:

1. Support for the Dropbox SDK endpoints will need to be added to `client.DropboxClient`. I have already added the methods  `create_shared_link`, `revoke_shared_link`, and `list_shared_links`.
2. Support for the errors raised by the Dropbox API endpoints `sharing/create_shared_link`, `sharing/revoke_shared_link`, `sharing/list_shared_links`. Those errors are documented in the [Dropbox API docs](https://www.dropbox.com/developers/documentation/http/documentation) and [Dropbox SDK docs](https://dropbox-sdk-python.readthedocs.io/en/latest/). You can have a look at how error conversion is handled in general in the `client` module and then add the if-clauses for any new error types. You may have to introduce new Maestral error types as well.
3. Add a high-level Maestral API. The daemon uses [Pyro5](https://github.com/irmen/Pyro5) for inter-process communication. This means that all arguments and return types need to be builtin Python types.
4. Add a command line interface. I was thinking about adding a new command group `maestral shared-link` with appropriate sub-commands.

Let me know if you have any specific questions about either of those steps. I'll be happy to help.

**Comment by DMR-coding** [comment]
What is the proper way to run my working copy of the application?

**Comment by SamSchott** [comment]
I've added a [getting started](https://maestral.readthedocs.io/en/latest/) section to API docs which will hopefully be helpful.

**Comment by SamSchott** [comment]
Also, I would recommend to install your version in a virtual environment and run it from there. It will still access the same config files but you can continue to use the stable version for syncing while working on the development branch.

**Comment by DMR-coding** [comment]
Just an update since I spoke up on this bug-- unfortunately my time has become very fractured due to a layoff. I still hope to get involved in this project, but I can't promise any particular level of timeliness at this point. Sorry about that.

**Comment by SamSchott** [comment]
@DMR-coding, sorry to hear about this. Don't worry about a specific timeline, I welcome all contributions however fast or slow they come. Just let me know if / when you'd like to get involved!
