### ISSUE TITLE
Memory creeping up

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral#248]
**Describe the bug**
In the course of the latest releases (around 1.2 onward), I noticed that `maestral` uses quite more memory than before upon start (~85MB vs ~55MB previously), and that memory starts further creeping up as the dropbox folder is being used. For example, right now it is ~195MB. This is close to using the official dropbox solution; to be fair, the official dropbox app still has higher memory usage (not horribly much), but it also uses its GUI frontend, while I am only running maestral daemon and cli (no Qt GUI).

**To Reproduce**
Run maestral daemon on linux and use it for a while - I guess numbers may differ due to size / usage, etc.

**Expected behaviour**
Maestral is lean and mean, like I recall in the old days.   :(

**System (please complete the following information):**
 - Maestral version: 1.2.1.
 - OS: Arch.
 - Desktop environment: 3.38.1
 - Qt version: N/A

**Additional context**
It is not really a serious issue, to be honest, but it does bring forth the natural question of what the advantage is right now (on linux, at least) vs the official dropbox solution.

**Comment by SamSchott** [comment]
> It is not really a serious issue, to be honest, but it does bring forth the natural question of what the advantage is right now (on linux, at least) vs the official dropbox solution.

At least on macOS, it comes without the entire electron framework. Here, we are competing against 500 MB of memory usage...

But you are right, I have observed some memory creep as well. There are a few effects at play:

1. The switch to an sqlite database has increased the base level of memory usage. This is due to using sqlalchemy. Its the state of the art for interacting with relational databases from Python but its a large library.
2. The Dropbox SDK keeps adding new futures, leading to a larger code base loaded into memory.
3. Python memory management is not great when working with many small strings such as file paths. Some of the freed up memory is not returned to the OS, resulting in the creep that you are seeing. I am not sure how Dropbox solved this (their sync engine is also written in Python). Maybe they use a custom memory allocator.

v1.2.2 reduces some of the memory creep by loading fewer index entries intro memory at once and garbage collecting unneeded objects earlier when they are freed.

If you are looking for other reasons to stick with this project, there is of course the option of "mignore" files, the nicer CLI, and the less stringent requirements on file systems and platforms :) I started this project originally when Dropbox dropped support for many common file system. They have of course reintroduced some of it now.

**Comment by coxackie** [comment]
many thanks, and I am absolutely grateful for your work. I understand it mostly benefits Mac users, but there are merit for Linux users as well, for sure.

 I think the Dropbox devs re-wrote part of the sync engine in Rust, from what I have read lately. This could have made miracles with memory, as Rust has (arguably) the best memory management you can ask for. Not to mention safety and speed.

 Anyway, I figured memory increase (at least initially) must have something to do with sqlite, since it happened recently. On the other hand, it is a much better indexing solution.

**Comment by SamSchott** [comment]
>  I think the Dropbox devs re-wrote part of the sync engine in Rust, from what I have read lately. 

That would explain recent improvements!

I have been profiling memory usage during reindexing and downloads and it seems like pure reindexing (deleting the entire index and rebuilding it from the server) actually is quite memory efficient. Sure, using SQLAlchemy increases the baseline but does seem to result in any leaks or incremental increases while syncing.

On the other hand, actually downloading files from the remote server does result in memory creep. Especially this line allocates some memory which is never released:

https://github.com/SamSchott/maestral/blob/cf92729f90679100cd3de93ddac298d2854b6f0d/src/maestral/sync.py#L3054

I suspect the issue may lie with freeing memory which is used by `requests`. This will be less significant for normal metadata fetches but more pronounced for full downloads. Actual downloading and writing to the drive is carrier out in chunks of 2**16 bytes but it will still add up for many parallel downloads if not fully released.

**Comment by SamSchott** [comment]
Memory management should be finally and thoroughly improved in v1.4.4.
