### ISSUE TITLE
brew support

### ISSUE THREAD

**Issue by drFDC** [SamSchott/maestral#258]
Hi Sam,

I just love love love your app, the original dropbox app uses a lot of memory and keeps connecting to a lot of domains. Thank you.
I was just wondering if you'd consider making a homebrew tap?

**Comment by SamSchott** [comment]
@drFDC, I am glad you like it!

There are currently no plans to distribute via homebrew. This is partially because I have no experience with creating taps.

Are you thinking about distributing the binary / app bundle via homebrew or the Python package? As far as I can see, the former would not have any advantage over downloading from GitHub releases, apart from an easier update process. The latter would not have any advantage over a pip-install but may introduce issues with the availability of dependencies and their resolution.

**Comment by drFDC** [comment]
I was mainly thinking about the binary and the update advantage, then again as long as you don't start to update the app every week this works fine as well.

**Comment by franklouwers** [comment]
FYI: https://github.com/Homebrew/homebrew-cask/pull/107842

**Comment by franklouwers** [comment]
@SamSchott are you open to a PR on README.md that mentions that one can now install maestral using Homebrew? ;)

**Comment by SamSchott** [comment]
@franklouwers, amazing, many thanks for setting this up! This is especially useful in the absence of an automatic update mechanism for the binary.

Yes, I am happy to include homebrew instructions in the README.

**Comment by franklouwers** [comment]
https://github.com/SamSchott/maestral/pull/427
