### ISSUE TITLE
[BUG] Dropbox folder not found after reboot

### ISSUE THREAD

**Issue by jimliddle** [SamSchott/maestral#304]
**Describe the bug**
The Maestral folder location is on a micro sd card formatted to ext4 - no issues when first setting up and assigning maestral to use that card for its location. All proceeds as expected and it syncs fine.

On reboot Maestral shows a message that the DropBox folder has been moved (it hasn't) and that it needs to be reset. Pointing it at the same location as it was previously results in a screen asking to proceed with a merge.

Each reboot produces exactly the same workflow

**To Reproduce**
1. Allocate microsd card (formatted before hand to ext4) as location for Maestral DropBox folder
2. Sync files
3. Reboot

**Expected behaviour**
The expected behaviour is that Maestral simply silently checks whether there any files to sync with DropBox on reboot .

**System (please complete the following information):**
 - Maestral version: 1.3.1
 - OS: Kubuntu 20.04
 - Desktop environment: Plasma

**Additional context**

**Comment by SamSchott** [comment]
Just a few questions to trouble shoot:

1) When you say "on reboot", do you mean when restarting Maestral or the entire PC?
2) The error message should specify the expected location of the folder. What it displayed there?
3) Can you check the config file at `~/.config/maestral/maestral.ini` manually? Is it actually updated with the correct folder location? I assume that writing to the config file is not a problem since your account ID, etc, are all remembered.

**Comment by jimliddle** [comment]
just to note the issue was resolved creating a static entry for the SD Card in fstab. This prevented it changing on reboot of the PC.

**Comment by SamSchott** [comment]
Thanks for the info!
