### ISSUE TITLE
Mac version update automatically

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#316]
Version 1.3.1

Mac version update automatically not by Appstore, there are libraries for it, I think Sparkle ? https://github.com/sparkle-project/Sparkle

Regards
Vlad

**Comment by SamSchott** [comment]
Yes, Sparkle is the way to go on macOS. I've just been holding off, trying to decide if adding the ~5 MB Sparkle framework and the extra code for the bundled macOS version is worth the effort. Alternatively I could go down the App Store route and modify Maestral to work as a sandboxed app (though managing folder access will be a bit cumbersome).

**Comment by cotfas** [comment]
Yes, App-store will give a more trust for other users, but not sure how will be the approval process for sandbox apps, if you use private-api you can forget about app-store :D.
~5mb on the app size I think will not be an issue, I normally dislike apps over 500MB which are simple apps, but for Maestral under 100MB on disk will not be any probl. The problem would be with the real-time cpu/ram usage, thats why I uninstalled the dropbox official app and switched to Maestral :).

**Comment by SamSchott** [comment]
The approval process should be manageable, I'm not using any private APIs. The issue rather lies in file system access by sandboxed apps. The only way to request access to a file or folder is through the "Open" dialog of the GUI. Because Maestral spawns a separate process for the sync daemon, the permissions will somehow need to be passed on to the daemon process, as far as I can tell. In addition, there is no equivalent way for CLI tools to request access to user folders. Therefore, CLI commands like the initial setup or `maestral move-dir` will not work.

So it's either sacrificing some CLI functionality for the convenience of the App Store, or using Sparkle and further fragmenting the code base between platforms and distribution channels...

**Comment by rorymullen** [comment]
In the absence of automatic updating, how should mac users who install via .dmg update? My guess:

1. wait for Maestral to idle
2. quit Maestral gui via menu bar
3. delete old version of Maestral.app 
4. download and install new [Maestral-x.x.x.dmg](https://github.com/SamSchott/maestral/releases)
5. start new version of Maestral.app

This process worked straight-forwardly for me. 

I also like the idea of auto updates, but I do see the size-function tradeoff. Thanks for developing this app!

**Comment by SamSchott** [comment]
@rorymullen, yes, that is pretty much it. You don't even need to delete the old version, when you drag Maestral over to the Applications folder it will replace the old app.
