### ISSUE TITLE
Excel content not synced to remote

### ISSUE THREAD

**Issue by riesentoaster** [SamSchott/maestral#337]
**Describe the bug**
When I change some content of a .xlsx-file on my computer, the changes are not picked up by Maestral and not synced up to Dropbox.

Creating new files/folders and changing file contents of txt-files both work correctly.

When the Excel-file is changed on Dropbox, the remote changes overwrite the local changes.

**To Reproduce**
Change something in a local .xlsx-file, watch the changes not appear on Dropbox, change something in the same file on Dropbox, watch it overwrite the local changes.

**Expected behaviour**
Local changes sync to remote correctly.

**System:**

 - Maestral version: GUI v1.4.2, daemon v1.4.2
 - OS: MacOS 11.2
 - Desktop environment: MacOS 11.2
 - PyQt version (for Linux GUI): ?

**Additional context**

**Comment by SamSchott** [comment]
Thanks for the report! I can reproduce this with recent Office versions on macOS 11, this definitely wasn't a problem previously. I suspect that Office apps have changed the way they save files.

The underlying issue is that saving the modifications is reported by the macOS FSEvents API as two consecutive events where the creation of the "new" file is reported first and the deletion of the "old" file is reported second. Taken together, it appears is if a temporary file was created and quickly deleted again and the sync daemon therefore ignores the reported events.

I have flagged this with `watchdog`, the library which we use to record file system events, at https://github.com/gorakhargosh/watchdog/issues/770, but I suspect that a workaround in Maestral will be easier.

**Comment by SamSchott** [comment]
Until the is fixed, the only workaround is to manually pause and resume syncing after saving any local changes. This will trigger a rescan and an upload of local changes which is independent of reported file system events.

**Comment by riesentoaster** [comment]
Thank you for the quick response and fix time!
