### ISSUE TITLE
Let user's choose Dropbox folder name

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#347]
Maestral Dropbox folder name defaults to "Dropbox (Maestral)" and there seems to be no way to change that.

Can we allow the user to change the folder name?

In particular, the space in between gives trouble in certain contexts.

**Comment by SamSchott** [comment]
It is possible, but currently only through the command line interface. You choose a custom name either when linking, or later with `maestral move-dir`. As long as you move the folder to a path within the same partition, this also shouldn't trigger any resyncs on most file systems.

The GUI currently doesn't support this. Dialogs to "chose an existing folder" and to "choose an existing file or create a new file" (save dialog) are very common and supported by most desktop environments but "choose or create a folder" dialogs are less common. I haven't found an elegant UI solution to do this yet that works well on most platforms. If you have any pointers or ideas, do let me know!

**Comment by raffaem** [comment]
> Dialogs to "chose an existing folder" and to "choose an existing file or create a new file" (save dialog) are very common and supported by most desktop environments but "choose or create a folder" dialogs are less common

Most dialogs "chose an existing folder" have a "create new folder" button. Mine certainly does.
1. Can't the output of "choose an existing folder" be taken as the _final_ folder, without appending "Dropbox (Maestral)" to it?
If I choose /media/dropbox, the folder should be /media/dropbox, not /media/dropbox/Dropbox (Maestral)
2. Alternatively, have a text box in the GUI with the name of the folder?

**Comment by SamSchott** [comment]
Fair point, option 1 is actually quite good. My other concern would be making the folder selection a two-step process: first create a folder, then select it. But this shouldn't be a problem because we provide a default choice `~/Dropbox (Maestral)` with a zero-step process. If someone wishes to customise the location, they have a higher chance of also wanting to customise the folder name.

**Comment by raffaem** [comment]
[Here is](https://unix.stackexchange.com/questions/643053/linking-a-dropbox-business-acccount-with-dropbox-firm-name-to-dropbox) another person that needs this feature

**Comment by SamSchott** [comment]
It's on my todo list...

**Comment by SamSchott** [comment]
@raffaem, the changes are now out in the prerelease versions on PyPI. I have tweaked the dialogs and warnings when choosing a non-empty folder accordingly - this should hopefully prevent users from accidentally deleting existing data if they are not too trigger happy with accepting dialogs.

Care to try this out and give some feedback? You'll need to explicitly install the pre-release version of `maestral-qt` as well.

**Comment by raffaem** [comment]
> @raffaem, the changes are now out in the prerelease versions on PyPI. I have tweaked the dialogs and warnings when choosing a non-empty folder accordingly - this should hopefully prevent users from accidentally deleting existing data if they are not too trigger happy with accepting dialogs.
> 
> Care to try this out and give some feedback? You'll need to explicitly install the pre-release version of `maestral-qt` as well.

Sure I will be your beta tester.

But how can I test the pre-release version without losing my folder or having to move it / re-download it?

**Comment by raffaem** [comment]
@SamSchott still waiting for instructions :)

**Comment by SamSchott** [comment]
Apologies for the slow response time, it's been a busy week.

Fundamentally, you'll need to do at least some re-downloading. The least intrusive way is probably to set up a new config (`maestral gui -c test`) which you can link to the same Dropbox account or a secondary account if you have one.

I am mostly interested to hear if the dialog messages are clear or ambiguous, both during the setup and when moving the folder later. The functionality itself should be working well now, it already went through a lot of manual testing.

**Comment by raffaem** [comment]
Sam,

it looks clear enough to me.

However I understand that most of the time the folder you pass in those applications is the "top folder" and the application will create a subfolder.

I would just insert some text before "if the folder is not empty"

"This will be the folder inside which your Dropbox content will be downloaded and synced. If the folder is not empty you will be given the option to merge it with your existing Dropbox or delete its content"

Honestly I would remove the option to delete the content. Either:
1. Merge existing content with Dropbox
2. Reject a non-empty folder altogether. Force the user to select an empty folder. This also makes clear what Maestral is doing. If the user wants to merge, he/she can copy the content over to the previously empty folder in a later step.

(I would vote for 2)

**Comment by raffaem** [comment]
Or maybe, in case of non-empty folder, we assume it is the "top folder" and display a message box that asks the user for the sub-folder name to create

**Comment by raffaem** [comment]
Another option.

Here:

![image](https://user-images.githubusercontent.com/54762742/116451516-d93c5700-a85c-11eb-8d63-fd06389bbf07.png)

I would do:

Select top folder:
[FOLDER DROPDOWN] ->$topfolder

Choose a name for the Dropbox subfolder:
[TEXT BOX, defaults to "Dropbox (Maestral)"] -> $subfolder

File folder name: $topfolder/$subfolder

**Comment by SamSchott** [comment]
Thanks for the suggestions! The underlying issues really is that platforms don't provide a nice "select an existing or create a new folder" dialog similar to the dialog for saving a file.

1. Allowing the selection of empty folders only: I like the simplicity of this approach and it will certainly work well for most use cases. The reason why I have kept the merge option around is for unlinking an account and relinking it later with the same folder. This allows the user to perform a merge which just brings the local and remote versions up to date with the respective changes instead of requiring to redownload everything. Granted this may be a niche use case. Conflicting files will be handled just like in a normal sync and created a "conflicting copy".
2. Removing the delete option: I am 100% with you there. Users can always manually delete a folder.
3. I thought about the option of providing two UI elements: one to select the parent folder and one for the folder name. But this isn't particularly elegant and just ads confusion to the most common case of accepting the default folder. 

I am wondering if the "Save file" panel can be somehow repurposed as a "select folder" panel. It already has a text field to enter a file name (-> use to enter a folder name) and comes with a default "already exists, do you want to replace?" dialog.

**Comment by SamSchott** [comment]
Done in v1.4.4.
