### ISSUE TITLE
[BUG] Tray icon is a white box if Maestral starts at login

### ISSUE THREAD

**Issue by elexx** [SamSchott/maestral#369]
**Describe the bug**
I checked "Start Maestral at login". Maestral starts and works, but the tray icon is only a white box

**To Reproduce**
See above. It happens at every login on my machine

**Expected behaviour**
Seeing the Maestral icon.

**System:**

 - Maestral version: 1.4.3 (GUI and daemon)
 - OS: Manjaro 21.0 Ornara
 - Desktop environment: Gnome 3.38.4
 - PyQt version: I'm sorry, but I don't know how to get the version of PyQt

**Additional context**
This is purely a cosmetic problem, Maestral starts and runs as expected, but the tray icon is just a white box (and yes, it seems the Bitcoint client faces a similar problem):
![systray](https://user-images.githubusercontent.com/221837/113824956-ae407500-9780-11eb-8a6f-60ed81480f5a.png)
After stopping and starting Maestral (via Gnomes default app launcher, eg .desktop file), the icon is as it should be:
![systray_after](https://user-images.githubusercontent.com/221837/113825278-11caa280-9781-11eb-8442-792d60741842.png)
However, if I start Maestral via the commandline (`maestral_qt` or `/usr/bin/python3 -m maestral_qt -c maestral`) the icon is black instead of white:
![systra_cmd](https://user-images.githubusercontent.com/221837/113826488-7fc39980-9782-11eb-98f6-c1ecf5f79d75.png)

I'm not sure but this might be related to #284. However, adding the `X-GNOME-xyz` lines (like in https://github.com/SamSchott/maestral/issues/284#issuecomment-803473008 and SamSchott/maestral-qt@d72e295f5a98897a8b2f1cc9f0609be2f70d2458) to the autostart file did not help in my case.

Please let me know if and how I can provide additional information.

**Comment by elexx** [comment]
I just found  #350: My PyQt version according to `pip3 show PyQt5` is 5.15.4.

**Comment by SamSchott** [comment]
System tray icons have been problematic in Gnome ever since native support has been removed. On Gnome 3.36 they seem to work fine when using the Appindicator extension. The same holds for Ubuntu which bundles the Appindicator extension.

Your success will vary with different versions of the Gnome shell and different system tray extensions. The situation is certainly not improved by Qt's flaky `QSystemTrayIcon` implementation. I suspect that the Bitcoin client also uses Qt for its GUI and therefore experiences similar issues.

Apologies for not being more helpful but this topic really is a rabbit hole. Chances are, it might resolve itself with future updates of Qt or the Appindicator extension...

**Comment by elexx** [comment]
No worries, I already had the feeling this bug is somewhere outside of Maestral. Thanks for having a look at the issue and thanks for Maestral!

**Comment by arkenoi** [comment]
Same issue -- blank square, xfce4/Xorg, Qubes OS, fedora 35 VM, blank icon. Python3-Qt5 may be either latest PIP version or Fedora package but the icon is not present anyway.
