### ISSUE TITLE
Commnad maestral not found on Fedora 34

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#382]
Sam,

I just switched to Fedora 34 and maestral doesn't work.
I installed with `pip3 install maestral[gui]`.

The installation is successful but neither the commands `maestral` nor `maestral_qt` exists.

Under `~/.local/share/applications/maestral.desktop` contains:
```
[Desktop Entry]
Version = {version}
Type = Application
Name = Maestral
Icon = maestral
GenericName=File Synchroniser
Comment = Sync your files with Dropbox
TryExec = maestral_qt
Exec = maestral_qt
Hidden = false
Terminal = false
Categories = Network;FileTransfer;
```

As you can see the version is a placeholder and typing `maestral_qt` in the terminal gives command not found. Of course clicking on Maestral from the application Overview does nothing

**Comment by raffaem** [comment]
I have tried to start Maestral as a module and got the following error. Not sure if this is another bug:
```
$ python3 -m maestral start
Starting Maestral...        [OK]
! Cannot load keyring keyring.backends.SecretService.Keyring. Please relink Maestral to get a new access token.
```

**Comment by SamSchott** [comment]
> The installation is successful but neither the commands maestral nor maestral_qt exists.

That's probably because the commands are not in your `PATH`. Pip will show at the end of the installation where Python's commands are installed. The exact location will depend on whether you installed a package for all users or just for yourself. In the second case, it will likely be `~/.local/bin`.

> Cannot load keyring keyring.backends.SecretService.Keyring. Please relink Maestral to get a new access token.

This means that it cannot access your keyring through the "SecretService" API (probably the Gnome keyring). Do you get a prompt to unlock your keyring when running this command? You'll also need to migrate your keyring entries from the old installation. Otherwise you will indeed need to unlink and relink Maestral. The linking process will then choose the most secure of the available keyring backends on your new setup. This is one of those cases where "merging" / keeping the current folder content is useful :)

**Comment by SamSchott** [comment]
Any luck in getting your environment to work again?

**Comment by raffaem** [comment]
Sam,
I will try again in the weekend and report back.
Thank you for the support !

**Comment by raffaem** [comment]
Sam,

had been very busy with work.

It's working now, and I can see the icon in the task bar after installing the Top Icons extension.

Thanks!

**Comment by SamSchott** [comment]
No worries, I'm glad its working now :)
