### ISSUE TITLE
Onboarding / text for initial folder choice is a little confusing

### ISSUE THREAD

**Issue by aaronrudkin** [SamSchott/maestral#404]
**Describe the bug**

After linking Maestral to a Dropbox account, you get the following text:

> Maestral has been successfully linked with your Dropbox account.
>
> Please select a local folder for your Dropbox. If the folder is not empty, you will be given the option to delete its contents or merge it with your Dropbox. In the next step, you will be asked to choose which folders to sync.

A few things here are not immediately obvious to me:

First, it's not immediately clear if I select a folder that already has files what the "merge" will do. I assume what it will do is upload all of the local files into the remote Dropbox before I select which parts of the remote Dropbox to then sync locally. What happens if local files already exist remotely (e.g. the local folder has `test.jpg`, but the remote Dropbox also has `test.jpg`)? My guess is that the local versions will clobber the remote versions. But regardless of what will happen, it's also unclear whether the consequences will have immediate effect or I'll get a separate dialog box asking me to confirm. I think the text should be unambiguous whether this is the point of no return, the same way a file copy dialogue would be. A bare minimum version of this might be once the user selects a folder that has files, to put a little piece of text below the folder selector saying "Folder contains <n> files, totalling <X> GB" or similar.

A special case of the above problem occurs because I currently have Dropbox (official client) installed. If I select the folder where I currently have Dropbox (official client) installed, which is `~/Dropbox`, and select to merge files with my Dropbox (remote account), will Maestral re-sync all the files in my local Dropbox (official client) folder to my remote Dropbox, potentially overwriting or messing up metadata and costing me a few hundred gigs of bandwidth?

If my local Dropbox (official client) is already doing selective sync, will this cause file loss of unsynced files -- e.g. will Maestral just "add" the local files, or will it rewrite the remote Dropbox to contain only the local files?

You do have some warnings on the site saying the clients should not be run concurrently, but it may be better to also make clear whether or not the folders can exist together or not.

If the user changes the default directory, there's no easy way to change it back -- since the `~/Dropbox (Maestral)` folder does not exist, the user would have to navigate to `~/`, then create `Dropbox (Maestral)`, then select it. Perhaps the dropdown could contain the currently selected folder, then a choice for the default option, then "Choose...". I don't know how much control you have over this component, it could be an OS-level dialog box, but if you have control.

The other thing that's a little unclear here, and I don't have a great solution for you, is that the default folder chosen is `~/Dropbox (Maestral)` (well, actually, expanded to `/Users/myusername/Dropbox (Maestral)`) and it actually wasn't clear to me at first visual glance that this was a different folder than `~/Dropbox` and not just selecting the `~/Dropbox` and having ` (Maestral)` as text in the dialog box. I am not sure how to make this clear. Maybe this is me being nitpicky.

If you do think Maestral can play nice with local Dropbox installs, it might make sense to actually check whether a Dropbox local install exists. If one does, you might default to that folder, and then further default the selective sync settings to exactly match what's currently in the local install folder. Still offer the user a choice to change, of course, but make that the default. But my guess there is no harmony between the two.

Okay, one last observation -- the text above uses "your Dropbox" in two different ways in the sentences. The first "your Dropbox" refers to "a local folder which will contain files synced with your remote Dropbox account". The second "your Dropbox" refers to "your remote Dropbox account". Maybe you could change the first sentence to "Please select a local folder to store files synced from your remote Dropbox account" and the second to ", or merge it with your remote Dropbox account" or similar. I am not wedded to "remote" or anything, just wanted to get you thinking about the language more carefully.

Sorry to open a UX issue that's not an actual code bug, I know on my own software I hate trying to think through this stuff, but I thought I'd start the conversation, see if any other users have thoughts. Hopefully this helps.

**Comment by SamSchott** [comment]
@aaronrudkin, your input is definitely helpful, I have been struggling with designing a simple and understandable folder selection dialog. In addition, due to popular request, it is now possible to freely select any folder name through the GUI where previously the folder name would be restricted to "Dropbox (CONFIG)" and you could only choose the location. While it gives users more options, it also introduces further complexity.

**Merging:**

> First, it's not immediately clear if I select a folder that already has files what the "merge" will do.

A merge will take place in two steps:

1. The remote Dropbox is indexed and all remote files are downloaded. If the content hash of a remote file corresponds to an existing local file, it won't be downloaded (saving bandwidth) but just registered as indexed. If there are remote and local files with the same path but a different content, a "conflicting copy" is created. If you have excluded a folder with selective sync, it won't be downloaded.
2. Any local files and folders that are not in the newly created index will be uploaded. If any local files / folders correspond to remote items excluded by selective sync, they will be renamed to a "selective sync conflict".

Metedata is generally not synced at all apart from "last modified" time stamps because the public Dropbox API does not expose any additional metadata such as extended attributes or permissions. I've been trying to convince the Dropbox team to at least expose file permissions in the API, without much success so far...

> it's also unclear whether the consequences will have immediate effect or I'll get a separate dialog box asking me to confirm

You won't get any future dialogs to confirm. The next dialog is only for selective sync. Is there anything in the GUI that suggests additional confirmation dialogs?

>  If I select the folder where I currently have Dropbox (official client) installed, which is ~/Dropbox, and select to merge files with my Dropbox (remote account), will Maestral re-sync all the files in my local Dropbox (official client) folder to my remote Dropbox, potentially overwriting or messing up metadata and costing me a few hundred gigs of bandwidth?

It will "resync" them but will not actual upload / download any files with equal content as in the remote / local, respectively. Metadata will be preserved if the files are actually equal.

 **Syncing to the same folder as the official client:**

> You do have some warnings on the site saying the clients should not be run concurrently, but it may be better to also make clear whether or not the folders can exist together or not.

I don't think that this will work well. Generally, Maestral will try to leave Dropbox caches and temporary files which live in `~/Dropbox/.dropbox.cache` alone. However, it does not preserve extended attributes when syncing and the official Dropbox client stores some sync info in those attributes (at least it used to). At the very least, you might end up with bad performance of the official client as it needs to regenerate some of its metadata.

If both clients are running at the same time, all bets are off.

**Improving the selection dialog:**

> Perhaps the dropdown could contain the currently selected folder, then a choice for the default option, then "Choose...". I don't know how much control you have over this component, it could be an OS-level dialog box, but if you have control.

I like this idea! That's certainly possible.

> it actually wasn't clear to me at first visual glance that this was a different folder than ~/Dropbox and not just selecting the ~/Dropbox and having (Maestral) as text in the dialog box

I'm not sure how to make this clear either. Suggestions are welcome.

> Okay, one last observation -- the text above uses "your Dropbox" in two different ways in the sentences. 

Good point!

> it's not immediately clear if I select a folder that already has files what the "merge" will do

I can see how this is ambiguous. But at the same time, there is not much space to elaborate here. Actually, the "delete" option was since removed, so I should remove that portion of the text. That should free some space for a brief explanation of merging.

**Comment by SamSchott** [comment]
What do you think of the following text?

> Please select a local folder for your Dropbox. If the folder is not  empty, you will be given the option to merge its content with your remote Dropbox. Merging will not transfer or duplicate any identical files.
>
> In the next step, you will be asked to choose which folders to sync.

**Comment by aaronrudkin** [comment]
Hey Sam,

Thanks for the great followup on this -- and sorry I left a few days without replying, I've in the middle of an international move and COVID offers some complications. I think the proposed text is solid, it definitely clears up the major confusion I had. Appreciate it.

**Comment by SamSchott** [comment]
The dialog text has been updated in the latest release. I'll add the default folder option to the dropdown menu at a later stage.
