### ISSUE TITLE
MS Office document adding (1)(1)(1)(1)(1)... to filename while editing on Mac

### ISSUE THREAD

**Issue by erseco** [SamSchott/maestral#407]
**Describe the bug**
While editing MS Office documents, p.e. Word, the filename is adding (1) to filename multiple times, maybe because the autosave feature.

**To Reproduce**
On macOS Big Sur (M1) edit a big document (1) and while you edit it check how the filename is appending (1)(1)(1)(1)...

**Expected behaviour**
Leave the filename as is

**System:**
 - Maestral version: 1.4.4 (but with previous the problem was the same
 - Python version: Python 3.9.5
 - OS: macOS
 - Desktop environment: macOS
 - PyQt version (for Linux GUI): Cocoa

**Comment by SamSchott** [comment]
Thanks for the report! Could you set the log level to `debug` and send me the output from modifying the word file?

I have trouble reproducing this myself but from looking at how the file is renamed, I can hazard a guess: When a modified version of a local file is uploaded and appears to conflict with a remote file, that file will be renamed as "conflicted copy". However, when a local file appears to be added, the remote conflict will be renamed by appending a (1). This will only occur when the sync daemon believes that the modified file is completely new.

Could you try and rebuild the index and see if the issue persists?

**Comment by SamSchott** [comment]
Many thanks, this is very helpful! It appears that the local index is properly updated after uploading local changes, however retrieving the index entry fails. Therefore the log entries reading:

> "/Programación/Programación didáctica - Seguridad y Alta Disponibilidad (ASIR).docx" appears to have been modified but cannot find old revision

I can reproduce this with a similarly named file so you might be right, it might be related to the special characters. I'll need to investigate further...

**Comment by SamSchott** [comment]
Yes, it's definitely the special characters. From what I can tell, the sequence of events is roughly as follows:

1. You initially create a Word file with a special character `ó` in the file name. This character really is a combination of `o +  ́`. Typical macOS apps (using proper platform APIs) should never create file names with such decomposed characters. Dropbox also does not like decomposed characters and save the file as `ó` instead on its servers. This looks the same but is only a *single* character.
2. The sync daemon notices that the file was renamed by Dropbox and renames the local file accordingly. The index is updated. All is well.
3. You modify the file in Word and save the modifications. At this point, the file is indeed saved to the new file name with the single character. However, the `FSEvents` API which we use to monitor file changes emits a `FileModifiedEvent` with the old path. The sync daemon thinks this is a new file.
4. Maestral attempts to upload the exiting file as a new file instead of a file change, Dropbox servers append a "(1)", we detect that and rename the local file.

For now, my only recommendation is to rename the file and remove the special characters. To fix this on our end, I'll need to make sure to perform the same unicode normalisation as Dropbox does before storing any paths in our database.

**Comment by erseco** [comment]
Thank you a lot, I renamed the filename, and it worked like a charm, best regards!
