### ISSUE TITLE
Sync from local to Dropbox after initial sync is not working at symlinked directory

### ISSUE THREAD

**Issue by jelenatko** [SamSchott/maestral#424]
Synchronization from local server to Dropbox is not functional after initial sync. Initial sync is ok, but when I add new file or folder in symlinked folder on local side it is not synchronized to Dropbox, from Dropbox side synchronization working. When I stop Maestral and start again, my changes from local are synced to Dropbox. Synchronization from regular folders working fine.

**System:**
 - Maestral version: 1.4.6
 - Python version: 3.6.8
 - OS: CentOS 7.9.2009
 - Desktop environment: without gui

fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 1024
fs.inotify.max_user_watches = 524288

Usage:        38.4% of 3.3 TB used
Status:       Up to date
Sync errors:  0

**Comment by SamSchott** [comment]
Yes, that is as expected. We currently don't get file system events for symlinked directories so they are only done when running a full scan (at startup or after a pause -> resume). See https://maestral.app/docs/symlinks.

Basically, I am ambivalent about how to treat symlinks, but the situation at the moment is certainly not ideal. In the mid-term, I'd like to do either of the following:

1. Not follow symlinks at all. Instead, sync the symlink file as-is. This would for example enable relative symlinks to folder inside the same Dropbox without duplicating any files. It could however be problematic when the user also syncs their files to a Windows PC.
2. Follow symlinks anywhere and explicitly request to receive file system events for (potentially nested) symlinked folders. This would be a bite more work to implement and we would need to handle corner-cases such as recursive symlinks. It would be annoying if the symlink points to another Dropbox folder but convenient otherwise.

**Comment by jelenatko** [comment]
Thanks for explanation, I moved data to one big hdd.
