### ISSUE TITLE
Installation seemingly worked - maestral not starting

### ISSUE THREAD

**Issue by WunschK** [SamSchott/maestral#439]
Hi, so I installed everything following these instructions (https://www.linuxuprising.com/2019/07/maestral-is-new-open-source-dropbox.html 
(I am on kubuntu 20.04)

but running maestral gui just results in maestral: command not found

If I run it from Pycharm terminal it works ... 

Am I missing something? 

All the best, 
K

**Comment by SamSchott** [comment]
I suspect that this is an issue with the location of the CLI tool not being in your path. Did you install it globally or only for the current user?

From the PyCharm terminal, `which maestral` will return the location of the command. You'll need to make sure that this is in on the paths returned by `echo $PATH`.

**Comment by WunschK** [comment]
I installed it for my user (only one on this machine) 
which maestral returns obvsly the Pycharm/project/venv/bin/maestral 
whereas 
echo $PATH returns nothing

**Comment by SamSchott** [comment]
Ahh, that explains things! You installed Maestral in a virtual environment of a PyCharm project. It will therefore only be found when that environment is active, for example from the PyCharm terminal in that particular project.

For it to be available in a standard terminal, you'll either need add `Pycharm/project/venv/bin` to your PATH, as you have done, or install it outside of the venv.

**Comment by SamSchott** [comment]
> added it to PATH, now whenever I enter maestral gui the cursor jumps to next line & nothing happens :-D

Nothing at all, not even an error message? This could again be an environment problem...

Can you install it regularly for the current user by running `pip3 install --user maestral[gui]` from a standard terminal, outside of a venv?

**Comment by WunschK** [comment]
nope, nothing: 
![maestral_gui](https://user-images.githubusercontent.com/64890303/129900904-bddf608a-9126-454b-a851-9bcfe9617b9a.png)

**Comment by SamSchott** [comment]
Not even a system tray icon showing up?

**Comment by SamSchott** [comment]
Also, please try installing in outside of a virtual environment, as recommended above!

**Comment by WunschK** [comment]
I think I just used pip install instead when installing it outside venv ... 
That's just stupid ...

**Comment by SamSchott** [comment]
Hrmp, in that case I am really not sure what the issue is. The following steps might help to narrow it down:

1. Did the GUI appear when running from the PyCharm environment? From your first comment, I understand that it did appear. If yes, did it also show a system tray icon? 
2. Did you complete the setup dialog previously? If yes, any subsequent launches of the GUI will not open any windows but just create a system tray icon. This tray icon might not be visible to under some configurations / conditions. I'm not very familiar with KDE settings though I do regularly test that the GUI works in KDE Neon.
3. Is the sync daemon running properly? You can test this for example by running `maestral status` in another terminal.

**Comment by WunschK** [comment]
Ah, sorry, I could have been clearer: 
After I installed it outside the pycharm env it worked, once I used pip3 install maestral ... 
before I only had tried pip ... 
Thanks for your personalised help and time :-)
