### ISSUE TITLE
'sparkle:shortVersionString' and 'sparkle:version' are not in Sparkle feed.

### ISSUE THREAD

**Issue by tjluoma** [SamSchott/maestral#451]
**Describe the bug**

The Sparkle feed is missing 'sparkle:shortVersionString' and 'sparkle:version' information

sparkle:shortVersionString = CFBundleShortVersionString

sparkle:version = CFBundleVersion

**To Reproduce**

View "<enclosure" part of Sparkle feed

**Expected behaviour**

I would expect to find `sparkle:shortVersionString="1.4.8"` and `sparkle:version="25"` in the feed, something like this:

	<enclosure
		url="https://github.com/SamSchott/maestral/releases/download/v1.4.8/Maestral-1.4.8.dmg"
		sparkle:edSignature="CPOyP/oLhviTu6zENVxoIIOwmIBMLRvEqPK1zjMQKdGWqP79EUz9/75JR0kXppn1Rl4KGNCAeUCmKBgbSAbHDg==" length="17374726"
		type="application/octet-stream"
		sparkle:shortVersionString="1.4.8"
		sparkle:version="25"
	/>

But the last two lines are not present:

**System:**

 - Maestral version: CFBundleShortVersionString: 1.4.8 and CFBundleVersion: 25
 - Python version: Python 3.9.7
 - OS: macOS / 11.5.2 / 20G95 (aka latest Big Sur build)

**Additional context**

I might be wrong, but I think that information is necessary for Sparkle to compare a new version against a currently installed version.

**Comment by SamSchott** [comment]
The `sparkle:shortVersionString` and `sparkle:version` are specified as part of the item itself instead of the enclosure:

https://github.com/SamSchott/maestral/blob/ef8a209e1532b5a45a6d8eab2079943aee60d54b/appcast.xml#L11-L12

According to Sparkle's docs [here](https://sparkle-project.org/documentation/publishing/#publishing-an-update), both should work and the current recommendation is to specify them as part of the top-level item: 

> Note on sparkle:version: Our previous documentation used to recommend specifying sparkle:version (and sparkle:shortVersionString) as part of the enclosure item. While this works fine, for overall consistency we now recommend specifying them as top level items instead as shown here. This is supported across all versions of Sparkle.

I can also confirm that updating worked for me during pre-release testing.

**Comment by tjluoma** [comment]
Thank you for the update! I was not aware of this new recommendation.. Not only that, I had somehow completely missed that they were present, just not where I was expecting them. I appreciate the explanation.
