### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by bobsica** [samschott/maestral#537]
**Describe the bug**
brew install maestral fails with error; retrying does not help

brew install maestral
==> Downloading https://github.com/SamSchott/maestral/releases/download/v1.5.2/Maestral-1.5.2.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/159194638/e2049bbb-88
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: f02cbfaea33173b6e2654d3764a6444b1ed64b9e335fbbb56e252beea55b8381
  Actual: f0bfa344ebc5a0cee425c61a1848c11ff3a82ef4e9e93c14fb9643846eb19c70
    File: /Users/xxxxxxxx/Library/Caches/Homebrew/downloads/0454f80f3d5afc605e6c3e5ef49cb1ef6aa61c010eeed150d53e642f9abd7552--Maestral-1.5.2.dmg
To retry an incomplete download, remove the file above. 

**To Reproduce**
installed homebrew
ran "brew install maestral"

**Expected behaviour**
I expect maestral.dmg to be available on my mac

**System:**
macos 11.6.1

**Additional context**
How do I fix this?

**Comment by EdogawaKun** [comment]
Same here.
macOS 12.0.1

**Comment by SamSchott** [comment]
Not sure what went wrong here, but I have a suspicion. Shortly after the releasing v1.5.2, I had to replace the macOS DMG on the GitHub releases page since it was missing a bundled dependency. Since this was not a change of the code, I only incremented the build number but did not create a new release. Homebrew might be checking the download against the SHA of the old DMG.

@franklouwers is in charge of the homebrew cask. @franklouwers, could this be fixed?

In the meantime, downloading directly from GitHub releases should work.

**Comment by AlexisSerneels** [comment]
Automatic update from within app is also broken and failing.

**Comment by SamSchott** [comment]
@AlexisSerneels, thanks for flagging this. I've just updated the Sparkle appcast to provide the correct hash.

**Comment by bobsica** [comment]
FYI I was able to download the release directly, install it, and it seems to work fine. Thanks.

**Comment by adidalal** [comment]
[This](https://github.com/Homebrew/homebrew-cask/pull/115141) should have resolved the issue

**Comment by samschott** [comment]
Closing since this is resolved now. Apologies for the trouble!
