### ISSUE TITLE
"Check for updates" timing not obeyed

### ISSUE THREAD

**Issue by Godatplay** [samschott/maestral#563]
**Describe the bug**
I have my preferences set to Weekly checking for updates, but I'm seeing Maestral perform frequent calls to api.github.com - it seems like roughly once every few minutes.

**To Reproduce**
1. Set check frequency low, such as Weekly.
2. Observe network traffic

**Expected behaviour**
Calls to api.github.com, and therefore update checking, occurs only as frequent as the preference states.

**System:**
 - Maestral version: 1.5.2
 - Python version: 3.8.9
 - OS: macOS 12.1
 - Desktop environment: Darwin
 - PyQt version (for Linux GUI): N/A

**Additional context**
Network traffic observed using Little Snitch, which shows Maestral calling to api.github.com via port 443.

Just wanted to conclude with saying I appreciate this software, seems solid so far!

**Comment by samschott** [comment]
The daemon will always check for updates roughly every 45 min, independent of the GUI, to display an update message in the command line if you are using the CLI. Those calls will be made to api.github.com. It currently does not respect configured update check intervals, maybe this should be improved.

If you are using the app bundle, update checks from the GUI will be carried out using Sparkle and will check the appcast at https://maestral.app/appcast.xml. Otherwise, calls will be made to the GitHub API as well. Those will respect the configured intervals.

**Comment by samschott** [comment]
This was fixed in v1.5.3.
