### ISSUE TITLE
Move-overwriting a file moves it to a conflicting copy locally, leaves the original in Dropbox

### ISSUE THREAD

**Issue by amptrofa** [samschott/maestral#570]
**Describe the bug**
After overwriting a file with another file using `mv`, Maestral moves the (new) file to a conflicting copy on the local file system. The original file is left in Dropbox (visible from Dropbox.com), but is not synced to the local filesystem.

This does not occur with other methods of overwriting a file, including saving (with every program I've saved from), redirection, appending, and even `cp`.

**To Reproduce**

```
$ touch foobar
$ echo "foo" > baz
$ mv baz foobar
$ ls
foobar
$ sleep 5
$ ls
'foobar (1)'
$ cat foobar\ \(1\)
foo
```
dropbox.com will now show an empty file `foobar` and a file `foobar (1)` with the contents `foo`. `foobar` is never synced back to the local filesystem.

**Expected behaviour**
The newly overwritten file contents are uploaded to Dropbox.

**System:**

 - Maestral version: 1.5.2 (also seen in 1.4.9, not tested in other versions)
 - Python version: 3.9.9 
 - OS: Debian Sid
 - Desktop environment: Openbox
 - PyQt version (for Linux GUI): N/A

**Additional context**
Similar to #319, but I don't see the old contents of the file synced back to the local filesystem.

Logs:
```
2022-01-08 18:13:43 sync DEBUG: Retrieved local file events:
[<FileMovedEvent: src_path='/home/adam/Dropbox/tmp/baz', dest_path='/home/adam/Dropbox/tmp/foobar', is_directory=False>]
2022-01-08 18:13:43 sync DEBUG: Filtered deleted events:
[]
2022-01-08 18:13:43 sync DEBUG: Filtered dir moved events:
[]
2022-01-08 18:13:43 sync DEBUG: Filtered other events:
defaultdict(<class 'list'>,
            {2: [<SyncEvent(direction=Up, change_type=Moved, item_type=ItemType.File, dbx_path='/tmp/foobar')>]})
2022-01-08 18:13:45 sync INFO: Upload conflict: renamed "/tmp/foobar" to "/tmp/foobar (1)"
```

**Comment by samschott** [comment]
Thanks for the detailed writeup. I can reproduce this on Ubuntu but strangely not on macOS. It likely has something to do with different file system events being emitted by inotify on Linux vs FSEvents on macOS. Let me investigate...

**Comment by Access-deny** [comment]
Centos 7, same sh*t.
The official dropbox refused to work because of the glibc version. I thought maestral could replace it, at least partially. I need to upload constantly updated files to the cloud. I have set in maestral settings:
upload=true
download=False
As a result, maestral renamed my files to somename.tar (conflicting copy).gz. And didn't upload anything to the cloud.
Great, what else. This is exactly what I need (sarcasm).

**Comment by Access-deny** [comment]
I renamed files:
find . -type f -name "*.tar (conflicting copy).gz" -exec bash -c 'mv "$1" "${1/.tar (conflicting copy).gz/.tar.gz}"' _ {} \;
But I also found 1 file: .tar (conflicting copy 1).gz with today's date. 
This file was created at the moment maestral was killed due to lack of memory (32 GB+16Gb swap was occupied by the maestral process)
Killed process 5147 (python3), UID 1000, total-vm:45571876kB, anon-rss:30970124kB, file-rss:0kB, shmem-rss:0kB

**Comment by Access-deny** [comment]
@samschott, explain, please, the reason for the conflicts. Why maestral can't just upload the files to the cloud and replace the current ones (isn't file versioning controlled by the dropbox cloud itself?). What would you advise in this case? We need versions of these files just like dropbox does and therefore we cannot remove them from the cloud.

**Comment by samschott** [comment]
@Access-deny, can you open a new issue for this? Complete disabling upload or download sync is currently not well supported and not really advertised, so you milage will vary. Those issues are unrelated to the original report here.
