### ISSUE TITLE
Fresh MacOS Maestral install never gets past "Connecting..." and therefore never syncs.

### ISSUE THREAD

**Issue by Fleckeri** [samschott/maestral#583]
**Describe the bug**

A fresh install of Maestral never gets past the "Connecting..." step, even after successfully linking to a Dropbox account (I can see my name and profile picture in the Preferences window). The "show sync issues" option shows no sync issues. Running `maestral log show` just shows it stopping at "Connecting...", which is also what `maestral status` shows.

Here's what I've tried without success: 
* Running the daemon via the terminal and the GUI. 
* Rebuilding the index
* Restarting the app
* Restarting my computer
* Unlinking/relinking my Dropbox account
* Reinstalling the app
* Connecting to different internet access points and connecting/disconnecting from different VPN servers

**To Reproduce**

1. Install Maestral from latest stable package downloaded from GitHub
2. Run setup as usual
3. Successfully connect to Dropbox account
4. The app status says "Connecting..." and never continues.

**Expected behaviour**

Maestral progresses past the "Connecting..." step and starts syncing files with my Dropbox account.

**System:**

 - Maestral version: 1.5.2
 - Python version: 2.7.16 and 3.7.2
 - OS: MacOS 12.1

**Additional context**

* When I run the suggested `python3 -c "from PyQt5.Qt import PYQT_VERSION_STR; print(PYQT_VERSION_STR)"` command, I get the following error:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5'
```

* I ran `brew install python` to make sure my Python3 was installed/up-to-date, but it hasn't helped. 
* Activity Monitor shows almost no disk activity from the Maestral processes. 
* My Dropbox is a bit over 35GB of data. 
* I have moved all the (synced) files from my default Dropbox folder to the Dropbox (Maestral) folder. 
* The regular Dropbox app has no difficulty connecting or syncing.

**Comment by samschott** [comment]
@Fleckeri, thanks for the report. This is certainly surprising and your trouble shooting steps were already quite exhaustive. In principle, Maestral should work well with both VPNs and Proxies but there might be some corner cases which I have not considered. Do you have any Proxies configured in System Preferences or otherwise?

Unfortunately, Maestral currently does not log why a connection cannot be established. Could you check if Dropbox servers are reachable via `curl` in the command line?
```console
$ curl -I "http://www.dropbox.com"
```
If this works, next step would be to install the requests package with `pip3 install requests` and try the following from a Python prompt:
```python3
import requests

res = requests.head("http://www.dropbox.com", timeout=2)
print(res)

proxies = requests.session().proxies
print(proxies)
```
This reproduces exactly the connection check that Maestral is doing. If this request returns `<Response [301]>`, all is well. If raises a `ReadTimeout` error, you can try to increase the the timeout  2 sec and see if this helps. Any other would also be useful to know! It would be also interesting to see what `requests.session().proxies` returns.

The PyQt5 version is only relevant for Linux, Maestral uses a native user interface on macOS.

**Comment by boettges** [comment]
> `$ curl -I "http://www.dropbox.com"`
> If this works [...]

What could be the reason for this not to work? (`curl` works in general, of course.)

I can rule out general network issues or corner cases since it is working on another device with the same connection configuration.

Maybe a lack of server-side authorization of this specific device is causing this?
Is it necessary to have installed and used the Dropbox client at least once ont he device before? That would be great to avoid on a new machine with a fresh install if possible.

Thanks a lot for the great work!

**Comment by samschott** [comment]
> I can rule out general network issues or corner cases since it is working on another device with the same connection configuration.

Well, *something* in the configuration will likely be different, even if it is a bit hidden. This could for example be environment variables with proxy settings that don't affect all programs.

> Maybe a lack of server-side authorization of this specific device is causing this?

Unlikely. The connection issues which you are seeing happens before Maestral tries to do anything for which it needs authentication.

> Is it necessary to have installed and used the Dropbox client at least once ont he device before?

Not necessary.

At the moment, the best shot at figuring this out is to run the Python code which I have posted in my previous comment, if you are comfortable installing Python packages and running some code. Otherwise, the next release will include better debug output for connection issues.

**Comment by Fleckeri** [comment]
> @Fleckeri, thanks for the report. This is certainly surprising and your trouble shooting steps were already quite exhaustive. In principle, Maestral should work well with both VPNs and Proxies but there might be some corner cases which I have not considered. Do you have any Proxies configured in System Preferences or otherwise?

I checked the my MacOS proxies, and none of the proxies are checked on. Passive FTP mode (PASV) is checked, though, and a couple local domains bypass the (non-active) proxies.

> Unfortunately, Maestral currently does not log why a connection cannot be established. Could you check if Dropbox servers are reachable via `curl` in the command line?
> 
> ```
> $ curl -I "http://www.dropbox.com"
> ```

Oddly enough, this doesn't work for me. The command simply stalls indefinitely until I cancel out of it. I tried a different command `$ curl https://www.gnu.org/gnu/gnu.html` and it worked immediately, so I tried `$ curl -I https://dropbox.com` and that instantly returned all the headers. Running a `curl` on the non-HTTPS domain just doesn't work for me for some reason (VPN off or on).

> If this works, the next step would be to install the requests package with `pip3 install requests` and try the following from a Python prompt:
> 
> ```python
> import requests
> 
> res = requests.head("http://www.dropbox.com", timeout=2)
> print(res)
> 

> 
> This reproduces exactly the connection check that Maestral is doing. If this request returns `<Response [301]>`, all is well. If raises a `ReadTimeout` error, you can try to increase the the timeout 2 sec and see if this helps. 

I ran the above commands in Python3, and it simply timed out. I increased the timeout to 30 seconds, and it still timed out.

Here's part of the error:

```python3
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='www.dropbox.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7e9dbd1860>, 'Connection to www.dropbox.com timed out. (connect timeout=30)'))
```

I ran the command again using `https://www.dropbox.com` and it returned a `<Response [200]>`.

> Any other would also be useful to know! It would be also interesting to see what `requests.session().proxies` returns.

This simply returns `{}`.

_____________

It seems like my installation really doesn't like the non-HTTPS version of the base Dropbox URL, and I'm not sure why. I must have screwed with my settings somewhere, but I'm not sure what it would be.

**Comment by samschott** [comment]
> It seems like my installation really doesn't like the non-HTTPS version of the base Dropbox URL, and I'm not sure why. I must have screwed with my settings somewhere, but I'm not sure what it would be.

That is very strange. The HTTP version of the URL should just respond with a redirect header to the HTTPS version. In fact, the next release will no longer check the connectivity using `http://www.dropbox.com` but will use `https://api.dropboxapi.com` instead. This should fix the problems which you are seeing 🤞

**Comment by Fleckeri** [comment]
> > It seems like my installation really doesn't like the non-HTTPS version of the base Dropbox URL, and I'm not sure why. I must have screwed with my settings somewhere, but I'm not sure what it would be.
> 
> That is very strange. The HTTP version of the URL should just respond with a redirect header to the HTTPS version. In fact, the next release will no longer check the connectivity using `http://www.dropbox.com` but will use `https://api.dropboxapi.com` instead. This should fix the problems which you are seeing 🤞

I appreciate it! I'll wait for the next version and report back here.

**Comment by Fleckeri** [comment]
Confirming Maestral version 1.5.3 has fixed this issue. Closing the issue now.
