### ISSUE TITLE
Change the format of the menu bar (tray) icons from PDF to PNG

### ISSUE THREAD

**Issue by lothar-cell** [samschott/maestral#688]
**Is your feature request related to a problem? Please describe.**
I'd like to change the menu bar icons to different ones, but since they are PDF instead of the commonly used PNG, I cannot reproduce the size properly.

**Describe the solution you'd like**
I'd like to see the format of the menu bar icons changed from PDF to PNG.

**Describe alternatives you've considered**
Tried to resize and convert PNG icons to PDF (18.7 x 18.7cm), but they were displayed very small in the menu bar.

**Additional context**
not applicable.

**Comment by tempelmann** [comment]
I believe they're PDFs because that's what macOS requires in order to support multiple resolutions and Dark Mode. I assume you're not using macOS, hence your difficulties. And that fact makes it unlikely that your request will be fulfilled.

I suggest you find a way to create a pdf from png with other tools that keep the icon intact.

**Comment by samschott** [comment]
@lothar-cell, I am aiming to use vector graphic formats for system tray icons since the system tray height is often variable, for example depending on scaling settings.

On Linux desktops, Maestral uses the more common SVG format. macOS has poor support for SVG on newer versions and no support at all on older ones. I'm therefore left with no choice but PDF there.

From your question, I am assuming that you are on macOS. Here, I'd recommend using open-source programs such as Inkscape can save directly to PDF. You can create vector graphics directly in Inkscape, or edit existing PDFs to crop any margins which likely make your icon appear "small" in the menu bar. Note that Preview's cropping tool does not remove the cropped parts of PDFs, it just "hides" them from display in Preview and possibly other PDF readers.

**Comment by samschott** [comment]
Closing as a shift to PNG is not planned. However, I do hope the alternative options above will be viable.

**Comment by lothar-cell** [comment]
Thanks for the tips samschott, I managed to export a matching sized pdf with a black icon on white background, but in the menu bar a full black square shows up. Any tips why that might be and how to avoid it?

**Comment by samschott** [comment]
If I recall correctly, the background needs to be transparent instead of white since template images only care about transparency / alpha channel and not the color. See https://developer.apple.com/documentation/appkit/nsimage/1520017-template.

**Comment by lothar-cell** [comment]
Thank you, it worked. It looks kinda bad though, to be honest I tried to replace the icon with the original dropbox one, but it looks weird, more pixelated, also I guess it doesn't fit onto the canvas properly, even though I maxed the space out.

![Screenshot 2022-06-12 at 20 40 18](https://user-images.githubusercontent.com/2356354/173248310-a34557bc-40ed-4bb7-bdec-0e639a4938f3.png)

Anyway, I don't expect you to give support on this, if you have better things to do:)

**Comment by samschott** [comment]
That does look a bit funky. It's likely some issue with the PDF export, however, this is really not my area of expertise. I'm afraid you will need to figure this out yourself!

**Comment by lothar-cell** [comment]
No problem!
