### ISSUE TITLE
Maestral 1.6.3 dropped support for macOS High Sierra (10.13)

### ISSUE THREAD

**Issue by Jack20947** [samschott/maestral#698]
**Describe the bug**
Maestral 1.6.3 dropped support for macOS High Sierra (10.13)

**To Reproduce**
The updater/installer says that for version "63" at least macOS 10.14 is needed

**Expected behaviour**
Support macOS 10.13

**System:**

 - Maestral version: 1.6.3
 - OS: macOS 10.13

**Additional context**
Please re-add support for older macOS.

**Comment by tempelmann** [comment]
I agree. The critical bug fix for the "v1_retired" issue should be applied to all macOS versions that were able to run version 62.

macOS 10.13 is still quite popular because it's the most stable version that still runs 32 bit apps. There are good reasons why people don't want to upgrade to 10.14 (both are now unsupported by Apple, so it makes little difference in that regard).

**Comment by samschott** [comment]
Apologies, this must have been an oversight when updating the Xcode project. I don't recall a strong reason to bump the version number and am happy to revert to support 10.12 higher.

Note however that once the app bundle switches to using Python 3.11 at some point in the future, it will also bump its minimum requirement to macOS 10.15. This is because the Xcode project and Python support libraries are taken from the upstream [beeware](https://beeware.org) project which has recently bumped its macOS minimum requirements (for a number of subtle but good reasons related to building on M1 macs).

**Comment by samschott** [comment]
Ok, I've pushed a new build for macOS 10.12 and higher which should show up in the Sparkle updater as well.
