### ISSUE TITLE
Documentation on Docker setup seems to cause unwanted files to be uploaded

### ISSUE THREAD

**Issue by atamis** [samschott/maestral#716]
**Describe the bug**

The documentation recommends mounting your desired Dropbox folder into the Maestral container at the `/docker` path.

```sh
$ docker run \
  -d \
  --name maestral \
  --rm \
  -v /mnt/dropbox:/dropbox \
  maestraldbx/maestral:latest
```
(https://maestral.app/docs/installation).

I did this on 2 separate machines and found that they fairly quickly stopped syncing and errored out. I don't have the precise error recorded, but it was specifically complaining about the Maestral database, and I couldn't get either of them to sync until I had rebuilt the index. It looks like Maestral was uploading `.local/share/*` from the container to my Dropbox folder. The 2 Maestral containers would overwrite each other or generate conflicting copies, and would eventually crash.

Maestral also seems to upload changes to this database with some regularity and logging to the same folder regularly, flooding the caches of my regular Dropboxes with old files. 

**To Reproduce**

Run 2 copies of the Maestral docker container attached to the same Dropbox. They should be run on different Dropbox directories, but both should mount the Dropbox directory into the container under the path `/dropbox`.

**Expected behaviour**

Both Maestral containers should sync files correctly and without interruption.

**System:**

 - Maestral version: 1.6.3
 - Python version:  3.10.1
 - OS: Alpine 3.15 (Python container)
 - Desktop environment: N/A
 - PyQt version (for Linux GUI): N/A

**Additional context**

It looks like this is caused by the fact that `/dropbox` is the container user's home folder, causing it to store its internal state (and some `python_keyring` related files) in the Dropbox folder and upload them. Note that this also seems to affect the `.config/maestral` directory and the `.cache/maestral` directory.

I found that I could resolve these issues by adding the following lines to my `.mignore` file:

```
.local/share
.config/maestral
.cache/maestral
```

**Comment by samschott** [comment]
Thanks for flagging this! The Docker container setup was actually a contribution by someone else and I must admin that I'm not particularly familiar with Docker. That being said, from the [Dockerfile](https://github.com/samschott/maestral/blob/master/Dockerfile) and the installation instructions:

1. You are correct,`/dropbox` is the home folder. Config files, the index database, etc, will accordingly be stored at `/dropbox/.config` and similar locations. Actively syncing those will be problematic.
2. If I read the installation instructions correctly, they should result in a folder `/dropbox/Maestral` being created **inside** the home folder to contain the synced Dropbox. You should be able to choose that folder name yourself when running `docker run -it -v /mnt/dropbox:/dropbox maestraldbx/maestral:latest ash` during setup. Was this not the case for you?

That being said, I can see two potential improvements:

* Provide better setup instructions for the Docker container. At the moment, the instructions only provide a list "magic" of commands to copy-paste without explaining what they'll do and why they work.
* Safeguard against choosing a Dropbox folder which may also contains some of Maestral's config files. This will always lead to trouble.

If you are up for it, I would very much welcome a PR to improve the setup instructions!

**Comment by atamis** [comment]
Okay, part of the problem is definitely that I didn't read the Docker instructions carefully enough and did not realize that the Maestral directory was supposed to be a subdirectory of the mounted volume. 

It's not really clear how I managed to get Maestral running without this, but the setup commands don't really get Maestral running, they just get the container running. The Docker documentation mentions booting a container with `ash` to setup Maestral, but doesn't mention how to set up Maestral. I have now figured out that you're supposed to run `maestral start` which runs a setup wizard, but I definitely didn't do that, so I don't know how I got things working. Beginning to wonder if this is a "me" issue.

I'm definitely open to contributing to the documentation. I'm thinking about mentioning the `maestral start` setup wizard. I'm also thinking of drawing attention to the fact that the user could store Maestral's config and data separately: have a volume mounted to `/dropbox` for Maestral's config and then mount the Dropbox folder itself to somewhere else, and set it up that way during the wizard.

Of course, aside from the fact that it doesn't work by default, storing all of Maestral's state and data in a single directory is convenient. Do you think it would be appropriate to mention that option even if it requires a `.mignore` file?

**Comment by egoebelbecker** [comment]
I looked in the repo for the Installation docs on the site. I was interested in contributing them.

I was also looking for the docs on the .mignore file. It would be easy to add to the image as part of the build process, and I could submit a PR. But I can't find the format or location.

**Comment by samschott** [comment]
Its not a "you" problem, its defiantly a documentation problem :)

> I'm definitely open to contributing to the documentation. I'm thinking about mentioning the maestral start setup wizard. 

Agreed, this makes sense.

> I'm also thinking of drawing attention to the fact that the user could store Maestral's config and data separately: have a volume mounted to /dropbox for Maestral's config and then mount the Dropbox folder itself to somewhere else, and set it up that way during the wizard.

`/dropbox` is set up to be the home folder of the user within the docker container and the setup flow will always default to creating a Dropbox folder there. Instructions which suggest another setup might end up being confusing and I am not sure how much value there would be. Maybe it is sufficient to call out where config files will live and let people with Docker experience draw their own conclusions.

> Do you think it would be appropriate to mention that option even if it requires a .mignore file?

I would advise against that. First, it exposes users to errors when either they or someone else modifies or accidentally deletes the `.mignore` file. Second, it puts a lot of trust in the `.mignore` mechanism always working perfectly. It **should**, but if there are any regression bugs ever introduced, it will be harder for users to recover from issues because their sync index and config may become messed up.

The documentation lives in the `website` branch and is written in markdown. The installation instructions in particular can be found at https://github.com/samschott/maestral/blob/website/_docs/installation.md. I'm looking forward to seeing the improvements!

**Comment by pataquets** [comment]
Docker image at its default configuration places Maestral's files listed by the OP (`.local/share/` and `.cache/`) in the Dropbox root folder.
I was experiencing an endless upload loop because of "file changes->maestral own files' update->new changes detected (own Maestral's files)->file uploads" when using the Docker image.
Adding the OP's files to the `.mignore` stopped it.
@samschott: I'm afraid this might be happening in all Docker installs.

**Comment by AN1MATEK** [comment]
Sorry to come back to this old issue, but this is still happening today. Should I open a new issue to propose a solution? Ideally, there would be a /config path where the configuration is stored, which is standard in docker. Thank you. 

Edit: this is how I got it setup, it works well this way. 
<img width="735" height="187" alt="Image" src="https://github.com/user-attachments/assets/c3ffb4d6-3e8e-431e-a2ff-21b2ed7f5b10" />
