### ISSUE TITLE
M1 Mac Mini not syncing entire dropbox. help! 

### ISSUE THREAD

**Issue by yourprettyfaceisgoingtohell** [samschott/maestral#718]
Maestral is not syncing my whole dropbox. Admittedly its over 15tb but it hasn't moved for days past 3.8tb. I moved to Maestral after constant kernel panics running the native dropbox app, and that has all gone away thanks to Maestral, it hasn't crashed but nothing is happening. it just isn't moving. its syncing locally to a black magic multidock running raid 0 with 4x 4tb Samsung drives formatted Mac OS journaled. 

I have tried rebuilding the index. unlinking and relinking the dropbox, restarting the machine, checked the internet connection, not sure what else I can do. it looks like everything is fine, no sync issues reported, but its just not working.

I am on a M1 Mac mini, the OS and Maestral are the latest updates. I am totally confused here. can someone help? I would really appreciate it.

**Comment by samschott** [comment]
Hi @yourprettyfaceisgoingtohell, this could potentially be issue server-side with Dropbox, I've seen cases in the past where the API started timing out after indexing > 100k remote files. The issue here does not seem to be the file / Dropbox size by rather the number of individual files and folders.

If you have the command line tool installed, you can open the logs by running `maestral log show -e` from a Terminal. This should either have a potentially useful error message, or at least show where Maestral got stuck. Could you post the last couple of log entries here?

If those are not helpful, the next step would be to adapt the log level to "debug" with `maestral log level DEBUG` and restart Maestral. Syncing will restart but the logs will now include a lot more detail about where and why it gets stuck. DEBUG logs may contain potentially sensitive information such as file names, please make sure that you redact anything sensitive before posting.

**Comment by samschott** [comment]
On the bright side, Maestral is not causing any kernel panics :)

**Comment by yourprettyfaceisgoingtohell** [comment]
hey sam, thanks for the reply. I ran that on terminal and its strange as it looks from here like everything is normal or am I reading that wrong? 

2022-08-23 20:51:48 sync INFO: Syncing ↓ 374/860
2022-08-23 20:51:55 sync INFO: Syncing ↓ 375/860
2022-08-23 20:52:02 sync INFO: Syncing ↓ 380/860
2022-08-23 20:52:19 sync INFO: Syncing ↓ 391/860
2022-08-23 20:52:21 sync INFO: Syncing ↓ 395/860
2022-08-23 20:52:33 sync INFO: Syncing ↓ 417/860
2022-08-23 20:52:38 sync INFO: Syncing ↓ 419/860
2022-08-23 20:52:42 sync INFO: Syncing ↓ 451/860
2022-08-23 20:52:48 sync INFO: Syncing ↓ 454/860
2022-08-23 20:53:13 sync INFO: Syncing ↓ 460/860
2022-08-23 20:53:17 sync INFO: Syncing ↓ 463/860
2022-08-23 20:53:39 sync INFO: Syncing ↓ 482/860
2022-08-23 20:54:34 sync INFO: Syncing ↓ 554/860
2022-08-23 20:54:41 sync INFO: Syncing ↓ 564/860
2022-08-23 20:54:59 sync INFO: Syncing ↓ 611/860
2022-08-23 20:55:03 sync INFO: Syncing ↓ 615/860
2022-08-23 20:55:06 sync INFO: Syncing ↓ 616/860
2022-08-23 20:55:08 sync INFO: Syncing ↓ 617/860
2022-08-23 20:55:25 sync INFO: Syncing ↓ 621/860
2022-08-23 20:55:31 sync INFO: Syncing ↓ 623/860

in any case the "show recent changes" dialogue is completely blank, and still no issues reported and the size of the dropbox folder hasn't budged either. 
 
any insights?

**Comment by yourprettyfaceisgoingtohell** [comment]
here is a grab from the debug, which again looks pretty normal no? 
![Screen Shot 2022-08-23 at 9 11 01 pm](https://user-images.githubusercontent.com/111864630/186266415-541257ab-c834-4eca-aa17-60d81beb66b3.png)

**Comment by samschott** [comment]
Yes, those all seem normal. At which point does syncing seem to get stuck? Could you wait until this happens and get the log output around that time? If you continue to see things progressing, maybe it is just being slow or rate limited by Dropbox.

**Comment by yourprettyfaceisgoingtohell** [comment]
Hi @samschott I spoke to dropbox and they say everything looks perfectly normal on their end also. any suggestions at this point would be extremely welcome. I am very confused

**Comment by samschott** [comment]
Yes, as in my previous comment: Could you wait until the downloads get stuck and get the log output from that time? As long as you see entries of the form of
```
2022-08-23 20:55:31 sync INFO: Syncing ↓ 623/860
```
there seems to be some progress made, even if slow.

**Comment by samschott** [comment]
Apologies for not coming back to this earlier. It's been a while now and there have been a couple of new releases in the meantime. I'll close this issue for now, but please feel free to reopen if it persists with v1.9.1.
