### ISSUE TITLE
A way for `maestral sharelink` to print just the URL

### ISSUE THREAD

**Issue by lgarron** [samschott/maestral#725]
**Is your feature request related to a problem? Please describe.**

I've been using `maestral sharelink create` and `maestral sharelink list`. They've very handy! But I keep running into the same UX issues:

- If you share some folders regularly, you have to try to remember whether a given folder was shared before, or try both commands.
- `maestral sharelink list` *truncates* listed URLs to fit in the terminal, making them useless for copying. :-/
- Even when given one specific file (or folder), both commands print extra info rather than just giving the URL.
- The commands only take paths relative to the Dropbox folder root, not absolute paths, nor paths relative to the current folder.

I've written myself a small script to work around these, but unfortunately it's still harder to use than I would like.

**Describe the solution you'd like**
For the first three bullets at least, it would be really nice to have something like a "create or list" command that simply prints the specific share URL for a given path.

This would allow copying directly to the clipboard, like this (on macOS):

```shell
maestral create --allow-existing --url-only "path/to/file/or/folder" | pbcopy
```

**Describe alternatives you've considered**
Finder integration might be nice, but that's probably more complicated: https://github.com/samschott/maestral/issues/580

**Comment by samschott** [comment]
Thanks for the detailed writeup!

Regarding `sharelink list`: I like the `--url-only` option. This command currently prints extra information, even when given a single path, because multiple links may exist for a single path if they grant different types of access (e.g., downloading vs viewing only, password protection, etc). In this case, there is added value in knowing how those links differ from each other.

Regarding `sharelink create`: IIRC, this should already return the URL only, without truncating. `--url-only` should therefore be superfluous. I can see how `--allow-existing` might be useful but there certainly will be some overlap with `sharelink list` in this case.

**Comment by samschott** [comment]
After some more thought, I am more inclined to change the default behaviour of `sharelink list` to print untruncated URLs only and introduce a `-l` option for more detailed output. This would be consistent with typical Unix "list" APIs as well as `maestral ls`.

Implementing `--allow-existing` for `sharelink create` has some subtleties involved because it will require checking for existing links with the requested properties if the creation failed. However, requested properties for a shared link do not always match with the actual properties of the resulting link, for example if the Team administrator has imposed some restrictions on how files may be shared. Therefore, finding the correct URL to return from possibly multiple options won't be trivial. I'm inclined to defer this one.

**Comment by lgarron** [comment]
> After some more thought, I am more inclined to change the default behaviour of `sharelink list` to print untruncated URLs only and introduce a `-l` option for more detailed output. This would be consistent with typical Unix "list" APIs as well as `maestral ls`.

That sounds reasonable! In the simple case, I *think* that would allow getting the URL for a specific path like this:

```shell
maestral sharelink create path || maestral sharelink -l list path | head -n 1
```
