### ISSUE TITLE
all symlinks are duplicated locally each time you rebuild index

### ISSUE THREAD

**Issue by smellymoo** [samschott/maestral#779]
**Describe the bug**
all symlinks held online are duplicated (conflicting copies) locally each time you rebuild index

**To Reproduce**
1) have symlinks already in the dropbox (online)
2) sync (download)
3) rebuild index

**Expected behaviour**
no conflicting copies of symlinks

**System:**
 - Maestral version: 1.6.4
 - Python version: 3.11.0
 - OS: Fedora 37
 - Desktop environment: KDE

**Comment by smellymoo** [comment]
I think this may be because when it downloads and creates the symlink, it creates a 0B file and not a symlink... So when you rebuild the index it doesn't match (failed download of symlink <-> real online symlink)

**Comment by samschott** [comment]
Thanks for the thorough report. I can reproduce this and the issue indeed lies with symlinks being downloaded as regular files, due to a peculiarity in how the Dropbox API provides file metadata in some cases. I've got a pending workaround now which should fix the "download" of symlinks and accordingly also any reindexing.
