### ISSUE TITLE
Login Items pref pane shows "Sam Schott" instead of "Maestral"

### ISSUE THREAD

**Issue by rdlugosz** [samschott/maestral#798]
**Describe the bug**
The Login Items settings menu in macOS Ventura (13.1) shows the developer's name instead of the app name. This led to a brief search of "who tf is sam schott and why are they h4ck1ng me?!?!"
<img width="827" alt="image" src="https://user-images.githubusercontent.com/402328/211321287-40db827f-1198-4dad-a577-20b129fb4259.png">

**To Reproduce**
With Maestral installed, open System Settings, General, Login Items

**Expected behaviour**
The entry for Maestral should be titled "Maestral"

**System:**

 - Maestral version: 1.6.4
 - Python version: above command failed with "No module named PyGt5"
 - OS: macOS Ventura 13.1

**Additional context**
No, I'm not sure why `ln` is a login item on my system but I'm guessing it's either Adobe's or Oracle's fault... The Java installer is especially persistent in adding login items - that garbage is getting removed as soon as I fix this client's legacy app...

Update: The `ln` command is courtesy of Docker and seems relatively innocent.

**Comment by samschott** [comment]
Ah, damn. It appears that macOS Ventura introduced changes to how Launch Agents should be registered. While the legacy method of just create a plist file in `~/Library/Launch Agents/` still works, System Settings don't correctly pick up the associated app in this case.

There appear to be two ways to mitigate this:

1. Use the *new* method of registering launch agents through [`SMAppService.register`](https://developer.apple.com/documentation/servicemanagement/smappservice/3945413-register) with the plist stored in the app bundle itself. This only works for macOS Ventura and app bundles, meaning special handling of previous releases and pip installs.
2. Set the `AssociatedBundleIdentifiers` key in the legacy plist to match the associated app. This is also new in Ventura but backward compatible.

I'm tending towards the second option since it is simpler to implement.
