### ISSUE TITLE
Syncing large dropbox account (30Tb)

### ISSUE THREAD

**Issue by ray-niptech** [samschott/maestral#832]
Connected to dropbox but with all folders EXCLUDED except for one folder that has only one file in it. It has been indexing for hours and is up to over 4 million and still going (14 hours so far)

I would expect the indexing to be very quick and sync the one file.

 - Maestral version: 1.6.5
 - Python version:  3.7.3
 - OS: [e.g. Ubuntu] Debian 10 (buster)
 - Desktop environment: [e.g. Gnome 3.32] None
 - PyQt version (for Linux GUI): None

I am wondering if the problem is fact at the dropbox end ?

**Comment by samschott** [comment]
Unfortunately, the problem is indeed on Maestral's end. It does index the entire Dropbox, even if only a few items are selected in Selective Sync.

There are a number of reasons for this, but the main one is that implementing resumable indexing is significantly simpler when indexing the entire Dropbox at once. This is mostly because of how the Dropbox API is designed.

There are ways around this, but none are trivial and I haven't had the time to implement any.

The upside is that even if you quit Maestral, it will resume indexing where it left off instead of starting from the beginning :)

**Comment by ray-niptech** [comment]
Hi Scott,

Thanks for getting back to me. 
It probably going to take another 2 days to finish syncing. It has already taken 3 days.

Following on from what you have said, what happens when the reindex_interval = 1209600 is reached ?

regards Ray

**Comment by samschott** [comment]
> Following on from what you have said, what happens when the reindex_interval = 1209600 is reached ?

It will reindex the entire 30 TB Dropbox folder. You might want to change that setting :)

**Comment by samschott** [comment]
Automatic reindexing has been removed now. Though the initial indexing behaviour will remain the same, unless there future changes to the Dropbox API will make it easier to skip items during indexing.
