### ISSUE TITLE
Editing large files while uploading previous version

### ISSUE THREAD

**Issue by DaAwesomeP** [samschott/maestral#848]
**Describe the bug**
I have a large binary file (2 GB) that is updated periodically. The size stays exactly the same but the contents and modified date of the file change. If the file is edited while Maestral is uploading it, then Maestral does not immediately detect this change. It will detect it after about 5 minutes or so. It will finish syncing the first change and the timestamp on Dropbox is the timestamp of the first time the file was edited. It is not clear to me if the uploaded file is corrupted (one part old, one part new).

**To Reproduce**

1. Create a large file.
2. Edit the file in-place while it is uploading.
3. Maestral will continue to upload, using the original changed timestamp.
4. The new change will not be detected for 5 minutes or longer.

**Expected behaviour**

In general, the file should probably always be checked for further changes as soon as it is done syncing (and maybe multiple times while it is syncing) instead of waiting for another re-scan of the directory or another event (I say this without knowledge of how specifically Maestral works). I think there is a high likelihood that many types of files may change during or right after it has last changed (i.e. an autosave, a log file, or someone hitting Ctrl+S on their document after every change, etc.).

It's not clear to me what happens when the file changes and if this results in corrupted uploaded data. Maestral should probably either copy the file (or maybe that is a bad idea) before syncing to ensure it does not upload half and half of a changed file. Or maybe it is as simple as canceling the current upload when the file changes and start over uploading. Maybe there is some compromise of copying the next 5MB of the file to be uploaded to RAM so that small-ish files can have multiple versions uploaded fully even if they change rapidly.

**System:**

 - Maestral version: v1.7.0
 - Python version: 3.10.8
 - OS: openSUSE Leap 15.3
 - Desktop environment: KDE Plasma 5.24.4
 - PyQt version (for Linux GUI): 6.4.2 via pip in a venv

**Additional context**

N/A

**Comment by samschott** [comment]
## How things work at the moment

Maestral sync process will lead to an *eventually* correct upload of the file, though you are right that any changes to the local file uploading may be picked up in an inconsistent manner. The sync logic will go through the following steps if a local file is modified:

1. A first modification event will be registered.
2. Maestral will wait until there have been no more events in the past 1 sec.
3. It will then queue all modified files for upload.
4. A new sync cycle begins after the all uploads have completed, waiting for new file events. Since the the last trigger.

This means an inconsistent upload is possible if a file is modified during upload, and if modifications affect parts of the file that were already read into memory *and* parts that have not yet been read. However, the file changes will result in another upload to be queued later. This cycle can of course repeat if you keep editing. Eventually, if you hold off on modifications for the duration of at least one upload, you will end up with a consistent file on the server.

If changes affect only parts of the file which have not yet been read, they will result in a consistent upload (but with a misleading modified time). They will also cause another upload to be queued later, but this upload will be skipped after comparing content hashes.

The public Dropbox API does not unfortunately support partial uploads or downloads, which results in a lot of unnecessary bandwidth usage if you have large files where only small parts are modified.

## To your suggestions

> Maestral should probably either copy the file

I've considered this. Depending on the platform's file system, this might work really well because copies are instantaneous and take no space (e.g., on APFS), or it might be a really bad idea because they are slow and resource intensive. I have so far been reluctant to introduce special logic dependent on the file-system.

> Maybe there is some compromise of copying the next 5MB of the file to be uploaded to RAM so that small-ish files can have multiple versions uploaded fully even if they change rapidly.

This is what is currently done, Maestral proceeds reading in 4 MB chunks. That being said, the caveat about only being able to "commit" entire files to Dropbox still applies, even if the upload itself takes place in chunks. The public Dropbox API does not support updating only byte-ranges of files. Though I have requested this.

**Comment by DaAwesomeP** [comment]
> any changes to the local file uploading may be picked up in an inconsistent manner

I think this should really be avoided. Since Dropbox stores versions of files, even if the final uploaded version is correct, the other versions will be deceivingly uploaded but corrupted.

> A new sync cycle begins after the all uploads have completed, waiting for new file events. Since the the last trigger.

I see, so it won't detect a change while it is currently uploading.

> However, the file changes will result in another upload to be queued later. This cycle can of course repeat if you keep editing. Eventually, if you hold off on modifications for the duration of at least one upload, you will end up with a consistent file on the server.

My experience was that it took several minutes _after the corrupted upload completed_ to detect that it should upload again. This is misleading because it looks like it has finished uploading (i.e. from the tray icon) for several minutes, but if you check Dropbox or the recent changes log then it has an old timestamp.

> I have so far been reluctant to introduce special logic dependent on the file-system.

Makes sense.

> That being said, the caveat about only being able to "commit" entire files to Dropbox still applies, even if the upload itself takes place in chunks.

I think this is fine and can have a workable solution even if the chunking is only done on the Maestral end when reading from disk.

Here is maybe a possible solution to the issue:

1. Detect an initial file change and store the current size of the file.
2. Copy first 4MB in memory and begin uploading.
3. Continue copying the next 4MB to memory and uploading. Every time the next chunk is copied to memory, check if the file has changed (just check modification time, file size, and if the file was deleted).
4. If the file has changed and the last chunk uploaded from memory was _not_ the last chunk (we know because we stored the initial file size), _then cancel the upload._ It should be canceled because there is no way to recover a complete uncorrupted file from this scenario.
5. Immediately start a new upload if the upload was canceled (don't wait for an event).
6. If the file has not changed, continue looping step 3.
7. Once the file has completed uploading successfully, still check one more time the file has changed (like in step 3, don't wait for an event).
8. Possibly: set a one-time timer for 10 seconds or so from upload completion to check one more time without waiting for an event. This would cause autosave and other similar functions to mayeb pick up file changes faster. Of course the number of concurrent timers should be limited.

**Comment by samschott** [comment]
I like that approach and agree that it will work better with Dropbox's concept of file versioning.

There are of course subtleties to take into account. E.g., immediately retrying to sync a file after each change may block other activity if a file is being continuously edited.

Note also that all file system events are picked up continuously by a separate thread, i.e., any modifications are detected and queued for processing almost immediately after they occur. However, there may be a delay to when sync threads start processing a particular event, for example because they are busy with other tasks, or because of connection issues.

**Comment by DaAwesomeP** [comment]
Yeah, I think most important part is cancelling the current upload and ensuring that a new upload gets scheduled somewhat soon, whatever that method may be. I do like the idea of restarting the upload right away, but I see what you mean with locking up if there are continuous changes for an extended period of time.

What if when it detects a change mid-upload it adds it to the _end_ of the queue? I think this makes sense since it is technically a later change than the rest of the items added to the queue since the upload started.

Is it possible that a file change event won't be added to the queue immediately if it is currently being uploaded? Possibly that is what I experienced. I think that should be solved by checking for changes on every chunk and adding to the end of the queue.

How many threads simultaneously upload files at one time? Is it a fixed number or dynamically scaled?

**Comment by samschott** [comment]
> What if when it detects a change mid-upload it adds it to the end of the queue? I think this makes sense since it is technically a later change than the rest of the items added to the queue since the upload started.

This is already what is happening at the moment, with the caveat that the current upload is not aborted.

> Is it possible that a file change event won't be added to the queue immediately if it is currently being uploaded? 

It's always added immediately to the queue. I am actually quite surprised by your experience that it may take > 5 min for the change to be picked up, unless there are other large file transfers happening.

> How many threads simultaneously upload files at one time? Is it a fixed number or dynamically scaled?

There will be at maximum 6 parallel transfers by default, though you can change that number in the config file.
