### ISSUE TITLE
Maestral Login Item does not advertise as Maestral

### ISSUE THREAD

**Issue by pierlo** [samschott/maestral#924]
**Is your feature request related to a problem? Please describe.**
The login item installed by Maestral is named "Sam Schott" under System Settings > General > Login Items.
   
**Describe the solution you'd like**
It would be preferable if it was named Maestral or something containing Maestral in the name: it would help the user identifying what this item is for. When looking for virus or investigating system performance, users can't easily make the link with Mestral.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by samschott** [comment]
This is due to a change in how login items are displayed starting with macOS Ventura, they now need to be explicitly associated with an app if they live outside of the app bundle.

I've updated the login item generation code, but you'll need to manually re-create the item by unchecking "Start on login" and then checking it again in Maestral's settings pane.
