### ISSUE TITLE
file gets deleted and re-added every ~20m

### ISSUE THREAD

**Issue by grahammitchell** [samschott/maestral#936]
**Describe the bug**

I use Dropbox on two machines: an Ubuntu desktop machine running the official Dropbox gui client, and a Macbook laptop running Maestral v1.7.3.

For the last couple of weeks, as often as every 20 minutes while I am using my laptop, a notification pops up on the other machine:

> You deleted Oye Cómo Va.odt

The file isn't actually deleted -- whenever I check it's still present on both the laptop and desktop machines.

The file hasn't been modified since March 2022, and there are about a hundred other similar files in the same folder. The version history feature on the Dropbox website shows:

> Deleted by Graham Mitchell
> 12:02 PM • API app

Then, less than a minute later:

> Oye Cómo Va.odt | Added by Graham Mitchell
> 12:02 PM | API app

I'm a software engineer and I've dealt with round-trip encoding issues before so my gut tells me it has something to do with the "o acute" character (`0xc3 0xb3`) and maybe even APFS, but who knows. I've opened a ticket with Dropbox support to confirm that the deletion is being initiated by Maestral on the laptop but the evidence points to that.

Here are the exact characters in the filename:

```
 % ls -1 Oye* | hexdump -C
00000000  4f 79 65 20 43 c3 b3 6d  6f 20 56 61 2e 6f 64 74  |Oye C..mo Va.odt|
00000010  0a                                                |.|
00000011
```

**To Reproduce**

🤷

**Expected behaviour**

I expect that it should leave the file alone. 😂

**System:**

 - Maestral version: 1.7.3
 - Python version: 3.11.3
 - OS: MacOS Ventura 13.4
 - Desktop environment: N/A
 - PyQt version (for Linux GUI): N/A

**Additional context**

I think I did pretty good above, but let me know and I'm happy to provide more. Here's a screenshot of the Dropbox version history page for this file:

![Screenshot of Dropbox history showing deletion and re-adding](https://raw.githubusercontent.com/grahammitchell/logs/master/Oye%20C%C3%B3mo%20Va%20delete%20re-add.png)

**Comment by grahammitchell** [comment]
Dropbox support finally finished their investigation, and they confirm:

> I can see that the deletions and re-adds are happening through Maestral.

**Comment by samschott** [comment]
Hi @grahammitchell, thanks for the report. I suspect that your hunch is correct it does have something to do with the special characters in the file name and how they are normalized by the Dropbox servers.

Since this is reproducible, could collect debug logs and share them here? You can enable debug logging with `maestral log level DEBUG` and view the logs in a text editor with `maestral log show -e`. After debug logging is enabled, those will contain detailed information about the sync events for each file and how they processed.

**Comment by samschott** [comment]
BTW, is the ls output from macOS or Linux? And do you see different unicode code points on the two machines?

**Comment by grahammitchell** [comment]
Hey, thanks for looking into this. I shut down Maestral, changed logging to `DEBUG`, then launched Maestral again, watched the dialog pop up, then shut down Maestral. I then deleted everything above that point in the log, since the file was pretty big.

https://raw.githubusercontent.com/grahammitchell/logs/master/maestral-graham-20230620-2.log

If you want the rest of the log, then that's in the same repo with a `-1`. It's too big for GitHub to display it raw, though.

The hexdump output I'd pasted in my original message was from MacOS. Here's the Ubuntu output:

**Comment by riesentoaster** [comment]
I ran across a similar issue: A folder with an umlaut (`ä`) in it got deleted and re-added randomly, which meant that, since it's a shared folder, my colleagues complained that I had deleted it.

I could trigger it by rebooting (not sure about just restarting Maestral).

I now downgraded to 1.7.2 and it seems to work as expected again.

(MacOS Ventura 13.4.1, MacBook Pro M1.)
