### ISSUE TITLE
Feature request: One-way syncing

### ISSUE THREAD

**Issue by fabiansvara** [SamSchott/maestral#95]
Maestral is fantastic, thanks a lot for your work on it! It's been a great improvement to my workflow.

Mainly, I use maestral to sync my code repo so that I can develop in my preferred desktop IDE, and run the code on any remote machine (e.g., on a compute cluster).

Since these remote machines tend to not have compatible filesystems, syncing from there to my main development machine is a bit broken.

For this use-case, it would be great if you could configure maestral to only sync from Dropbox to the local filesystem, but not do the reverse.

**Comment by SamSchott** [comment]
That should be quite easy to do, it's a matter of not launching the threads which process local file events. I see the most work the CLI or GUI interface to switch between sync modes.

Which file systems are you using and which issues have you been seeing?

There may also be some issues with git repos. I am hoping to handle the multiple and rapid file changes from git correctly, this will be one of the goals for Maestral to come out of "beta".

**Comment by fabiansvara** [comment]
The filesystem I'm having trouble with is GPFS. Basically it's a kind of network filesystem. I wouldn't expect it to work properly in the local-->Dropbox direction. Specifically what's happening is it doesn't detect file changes to upload (duh), but recently I've been getting a lot of these annoying "(conflicted copy)" files that Dropbox auto-generates as well. Not sure why that happens.

Syncing from Dropbox to GPFS works perfectly well, though.

**Comment by SamSchott** [comment]
Ah, yes, I don't think Maestral will work with GPFS. It will try to use inotify and should fall back to (slow) periodic scans of the Dropbox folder otherwise. This detection works by checking for inotify functions in the platform's libc and therefore might be misleading if the platform supports inotify but the file system does not use it. In any case, I would not recommend the fallback to periodic scans for large folders.

Nevertheless, when you resume syncing after Maestral has been paused or wasn't running, it will do a full scan of the Dropbox folder and check against its index if anything has changed. Changed files will be uploaded if their content hash differs from the one on Dropbox - this might create conflicted copies. Likewise, if you have remote changes trying to replace a local file with un-synced changes, this will create conflicts.

Neither Dropbox nor Maestral will create "conflicted copies" if the contents of the local and the remote file are equal. In case of folders, the are a few bugs in the current release...

**Comment by fabiansvara** [comment]
This feature would really be highly appreciated. I use maestral a lot on "unsupported" filesystems, and usually all is good, but weird issues do happen.

Most recently, I installed maestral on a new GPFS-based cluster node and the end result was that almost all of the files in my dropbox were deleted. I fully understand that both-way syncing on GPFS is fundamentally a problem, but one-way syncing is really all I need.

**Comment by SamSchott** [comment]
It's on my radar. I'm only undecided on how to handle conflict resolution for this. Possibly options:

1. Handle conflict resolution as normal: If a local file has been modified, move it to a conflicting copy before downloading the server version. This won't require any changes :)
2. Create all local files and folders as readonly. May not work on some file systems, e.g., NTFS.
3. Always overwrite local changes with the server version. This is a one way sync after all!
4. Let the user choose between some or all of the above options with a config flag.

Any preferences? I am reluctant to implement the last option, mainly because it means more work for possibly only a niche application.

**Comment by fabiansvara** [comment]
As far as I'm concerned, both (1) and (3) would work. Not sure how (2) helps, since you could always override that.

You're probably right it's somewhat of a niche feature, but I think it wouldn't be if more people knew about it. I'm pretty sure there's a lot of demand for putting dropbox on CIFS, NFS, SSHFS, etc ...; and if a fraction of the people who'd like to do that knew that one-way sync with maestral works great on those filesystems, that'd still leave a lot of cases where that would be fine.

**Comment by fabiansvara** [comment]
Thanks a lot, I really appreciate it!
