### ISSUE TITLE
NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by UInt2048** [samschott/maestral#965]
**Describe the bug**
![B5D3178D-2FD3-4F99-B0B5-EC77DF10605E](https://github.com/samschott/maestral/assets/46784000/c9d00c99-9504-4fa7-8df9-e9dc7c5c1d06)

**To Reproduce**
Open Maestral GUI, set http client to Firefox, and try to login to get authorization token

**Expected behaviour**
There should be an authorization token

**System:**
 - Maestral version: 1.8.0
 - Python version: 3.11.2
 - OS: Debian 12
 - Desktop environment: KDE Plasma
 - PyQt version (for Linux GUI): 6.5.2-1 (system provided)

**Additional context**
I used the break system packages option instead of a venv install. I don’t know if that would contribute to the issue.

**Comment by samschott** [comment]
The URL in your screenshot seems like a local cache file instead of an actual Dropbox URL. I've never seen that before but suspect some unintended interaction with Maestral trying to open the URL and some Firefox or KDE setting instead redirecting you to a cached file. Do you have any custom configuration that could cause this? Unfortunately, I don't have enough experience with KDE or a VM available to test this myself.

**Comment by UInt2048** [comment]
Thanks for the insight. It was indeed a KDE issue, and I was able to solve it! 🎉

People of the future, see AresValley/Artemis#29 for the solution.
